
# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

lego_module_list_first = [

]

lego_module_list_second = [
"drivers/input/touchscreen/goodix/berlin/goodix_ts_berlin.ko"
]

lego_module_list = [
"drivers/battery/battery_auth/ds28e30/sec-auth-ds28e30.ko",
"drivers/battery/battery_auth/sle956681/sec-auth-sle956681.ko",
"drivers/battery/charger/nu2111a_charger/nu2111a_charger.ko",
"drivers/battery/charger/s2mf301_charger/s2mf301_charger.ko",
"drivers/battery/charger/s2mf301_charger/s2mf301_pmeter.ko",
"drivers/battery/common/sb_wireless.ko",
"drivers/battery/common/sec-battery.ko",
"drivers/battery/common/sec-direct-charger.ko",
"drivers/battery/common/sec_pd.ko",
"drivers/battery/core/sb-core.ko",
"drivers/battery/fuelgauge/s2mf301_fuelgauge/s2mf301_fuelgauge.ko",
"drivers/dpu/panel/mcd-panel-samsung-drv.ko",
"drivers/dpu/panel/mcd-panel-samsung-helper.ko",
"drivers/fingerprint/fingerprint.ko",
"drivers/fingerprint/fingerprint_sysfs.ko",
"drivers/gpu/drm/samsung/panel/ana6710/mcd-panel-ana6710_a56x.ko",
"drivers/gpu/drm/samsung/panel/mcd-panel.ko",
"drivers/gpu/drm/samsung/panel/oled_common/usdm-panel-oled-common.ko",
"drivers/gpu/drm/samsung/panel/s6e3fc5/mcd-panel-s6e3fc5_a56x.ko",
"drivers/input/input_boost/input_booster_lkm.ko",
"drivers/input/sec_input/sec_common_fn.ko",
"drivers/input/sec_input/sec_input_notifier.ko",
"drivers/knox/hdm/hdm.ko",
"drivers/knox/kzt/kzt.ko",
"drivers/knox/ngksm/ngksm.ko",
"drivers/lego/lego.ko",
"drivers/mfd/slsi/s2mf301/mfd_s2mf301.ko",
"drivers/misc/drb/dev_ril_bridge.ko",
"drivers/muic/common/common_muic.ko",
"drivers/muic/slsi/platform/muic_platform.ko",
"drivers/muic/slsi/s2mf301/muic_s2mf301.ko",
"drivers/muic/slsi/s2mf301/top_s2mf301.ko",
"drivers/nfc/lsi/nfc_slsi_sec.ko",
"drivers/nfc/snvm/snvm.ko",
"drivers/phy/common/usb_repeater_module.ko",
"drivers/phy/nxp/ptn3222/repeater_ptn3222_module.ko",
"drivers/regulator/dio8018/dio8018.ko",
"drivers/regulator/et5917/et5917.ko",
"drivers/samsung/debug/sec_debug.ko",
"drivers/samsung/debug/sec_debug_base_early.ko",
"drivers/samsung/debug/sec_debug_dprm.ko",
"drivers/samsung/debug/sec_debug_dprt.ko",
"drivers/samsung/debug/sec_debug_dtask.ko",
"drivers/samsung/debug/sec_debug_extra_info.ko",
"drivers/samsung/debug/sec_debug_hardlockup_info.ko",
"drivers/samsung/debug/sec_debug_hw_param.ko",
"drivers/samsung/debug/sec_debug_kerror_report.ko",
"drivers/samsung/debug/sec_debug_mode.ko",
"drivers/samsung/debug/sec_debug_reset_reason.ko",
"drivers/samsung/debug/sec_debug_sched_info.ko",
"drivers/samsung/debug/sec_debug_sched_report.ko",
"drivers/samsung/debug/sec_debug_slab_info.ko",
"drivers/samsung/debug/sec_debug_softdog.ko",
"drivers/samsung/debug/sec_debug_stacktrace.ko",
"drivers/samsung/debug/sec_debug_test.ko",
"drivers/samsung/debug/sec_debug_wdd_info.ko",
"drivers/samsung/debug/softdog.ko",
"drivers/samsung/factory/sec_reloc_gpio.ko",
"drivers/samsung/pm/sec_thermistor/sec_thermistor.ko",
"drivers/samsung/sec_bootstat.ko",
"drivers/samsung/sec_class.ko",
"drivers/samsung/sec_crash_key_user.ko",
"drivers/samsung/sec_hard_reset_hook.ko",
"drivers/samsung/sec_key_notifier.ko",
"drivers/samsung/sec_reboot.ko",
"drivers/sdp/sdp.ko",
"drivers/sec_panel_notifier_v2/sec_panel_notifier_v2.ko",
"drivers/sensorhub/shub.ko",
"drivers/sensorhub/utility/sensor_core.ko",
"drivers/sensors_lego/isg5320a.ko",
"drivers/staging/android/switch/sec_switch_class.ko",
"drivers/sti/abc/abc.ko",
"drivers/sti/abc/abc_hub.ko",
"drivers/usb/common/vbus_notifier/vbus_notifier.ko",
"drivers/usb/notify/usb_notifier.ko",
"drivers/usb/notify/usb_notify_layer.ko",
"drivers/usb/typec/common/pdic_notifier_module.ko",
"drivers/usb/typec/manager/if_cb_manager.ko",
"drivers/usb/typec/manager/usb_typec_manager.ko",
"drivers/usb/typec/slsi/common/s2m_pdic_notifier_module.ko",
"drivers/usb/typec/slsi/s2mf301/pdic_s2mf301.ko",
"drivers/vibrator/awinic/aw8624x_v9/aw8624x_haptic.ko",
"drivers/vibrator/common/inputff/sec_vibrator_inputff_module.ko",
"drivers/vibrator/common/vib_info/vibrator_vib_info.ko"
]

lego_dtbo_list = [
"a56x_eur_open_w00_r04.dtbo",
"a56x_eur_open_w00_r02.dtbo",
"a56x_eur_open_w00_r01.dtbo",
"a56x_eur_open_w00_r00.dtbo"
]
lego_model = 'a56x'