# SPDX-License-Identifier: GPL-2.0
#
# This file should be included by external modules that need to link to this
# project.

KCFLAGS += -I$(KERNEL_SRC)/../exynos/device/mx/mx8855/include

EXTRA_SYMBOLS += $(O)/../exynos/device/mx/mx8855/Module.symvers
