# SPDX-License-Identifier: GPL-2.0
#
# Makefile for kernel External SPI drivers.
#

obj-$(CONFIG_SPI_S3C64XX_EXT)		+= spi-s3c64xx-ext.o

# Test Files
obj-$(CONFIG_SPI_S3C64XX_EXT_KUNIT_TEST) += test/
