# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_ARM_GIC_V3_VENDORHOOK)	+= irq-gic-v3-vh.o
obj-$(CONFIG_ARM_GIC_VENDORHOOK)	+= irq-gic-vh.o

subdir-ccflags-y += -I${ROOT_DIR}/${KERNEL_DIR}/drivers/irqchip
