# SPDX-License-Identifier: GPL-2.0
#
# Makefile for PMIC RTC class/drivers.
#

obj-$(CONFIG_RTC_S2P)   += s2p_rtc.o
obj-$(CONFIG_RTC_S2MPS27)   += s2mps27_rtc.o
obj-$(CONFIG_RTC_S2SE910)   += s2se910_rtc.o
obj-$(CONFIG_RTC_S2MPU15)   += s2mpu15_rtc.o
obj-$(CONFIG_RTC_AUTO_PWRON)	        += sec_pon_alarm.o
