# SPDX-License-Identifier: GPL-2.0
#
# Makefile for samsung regulator drivers.
#

# SoC PMIC
obj-$(CONFIG_DRV_SAMSUNG_PMIC) += pmic_class.o
obj-$(CONFIG_REGULATOR_S2P) += s2p_regulator.o
obj-$(CONFIG_REGULATOR_S2MPS27)	+= s2mps27_regulator.o
obj-$(CONFIG_REGULATOR_S2MPS28)	+= s2mps28_regulator.o
obj-$(CONFIG_REGULATOR_S2MPM07) += s2mpm07_regulator.o

obj-$(CONFIG_REGULATOR_S2SE910)	+= s2se910_regulator.o
obj-$(CONFIG_REGULATOR_S2SE911)	+= s2se911_regulator.o
obj-$(CONFIG_REGULATOR_S2MPA05) += s2mpa05_regulator.o
obj-$(CONFIG_REGULATOR_S2RP910)	+= s2rp910_regulator.o

obj-$(CONFIG_REGULATOR_S2MPU15)	+= s2mpu15_regulator.o
obj-$(CONFIG_REGULATOR_S2MPU16)	+= s2mpu16_regulator.o

# Etc PMIC
obj-$(CONFIG_REGULATOR_S2MPB02) += s2mpb02-regulator.o
obj-$(CONFIG_REGULATOR_S2MPB03) += s2mpb03.o
obj-$(CONFIG_REGULATOR_S2DOS05)		+= s2dos05-regulator.o
s2dos05-regulator-$(CONFIG_REGULATOR_S2DOS05)	+= s2dos05.o s2dos05_powermeter.o
obj-$(CONFIG_REGULATOR_S2DOS07)		+= s2dos07-regulator.o

#ETC
subdir-ccflags-y += -I${ROOT_DIR}/${KERNEL_DIR}/drivers/gpio
