/****************************************************************************
 *
 * Copyright (c) 2014 - 2024 Samsung Electronics Co., Ltd. All rights reserved
 *
 ****************************************************************************/

#include "mif_reg.h"

#define DBUS_BARAC_W_COUNT 1
#define PBUS_BARAC_W_COUNT 9
#define BARAC_BIT_SHIFT 12

const u32 dbus_baaw_offset[DBUS_BARAC_W_COUNT][5] = {
	{BARAC_D_WLBT_BA_WINDOW_CTRL0, BARAC_D_WLBT_BA_WINDOW_BASE_ADDR0, BARAC_D_WLBT_BA_WINDOW_END_ADDR0, BARAC_D_WLBT_BA_WINDOW_REMAP_ADDR0, BARAC_D_WLBT_BA_WINDOW_STATUS0},
};

const u32 dbus_baaw_value[DBUS_BARAC_W_COUNT][4] = {
	{BARAC_CTRL_VAL, WLBT_DBUS_BARAC_0_START, WLBT_DBUS_BARAC_0_END, 0 /* platform->mem_start */},
};

const u32 pbus_baaw_offset[PBUS_BARAC_W_COUNT][5] = {
	{BARAC_C_WLBT_BA_WINDOW_CTRL0, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR0, BARAC_C_WLBT_BA_WINDOW_END_ADDR0, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR0, BARAC_C_WLBT_BA_WINDOW_STATUS0},
	{BARAC_C_WLBT_BA_WINDOW_CTRL1, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR1, BARAC_C_WLBT_BA_WINDOW_END_ADDR1, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR1, BARAC_C_WLBT_BA_WINDOW_STATUS1},
	{BARAC_C_WLBT_BA_WINDOW_CTRL2, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR2, BARAC_C_WLBT_BA_WINDOW_END_ADDR2, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR2, BARAC_C_WLBT_BA_WINDOW_STATUS2},
	{BARAC_C_WLBT_BA_WINDOW_CTRL3, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR3, BARAC_C_WLBT_BA_WINDOW_END_ADDR3, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR3, BARAC_C_WLBT_BA_WINDOW_STATUS3},
	{BARAC_C_WLBT_BA_WINDOW_CTRL4, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR4, BARAC_C_WLBT_BA_WINDOW_END_ADDR4, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR4, BARAC_C_WLBT_BA_WINDOW_STATUS4},
	{BARAC_C_WLBT_BA_WINDOW_CTRL5, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR5, BARAC_C_WLBT_BA_WINDOW_END_ADDR5, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR5, BARAC_C_WLBT_BA_WINDOW_STATUS5},
	{BARAC_C_WLBT_BA_WINDOW_CTRL6, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR6, BARAC_C_WLBT_BA_WINDOW_END_ADDR6, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR6, BARAC_C_WLBT_BA_WINDOW_STATUS6},
	{BARAC_C_WLBT_BA_WINDOW_CTRL7, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR7, BARAC_C_WLBT_BA_WINDOW_END_ADDR7, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR7, BARAC_C_WLBT_BA_WINDOW_STATUS7},
	{BARAC_C_WLBT_BA_WINDOW_CTRL8, BARAC_C_WLBT_BA_WINDOW_BASE_ADDR8, BARAC_C_WLBT_BA_WINDOW_END_ADDR8, BARAC_C_WLBT_BA_WINDOW_REMAP_ADDR8, BARAC_C_WLBT_BA_WINDOW_STATUS8},
};

const u32 pbus_baaw_value[PBUS_BARAC_W_COUNT][4] = {
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_0_START, WLBT_CBUS_BARAC_0_END, WLBT_MAILBOX_AP_WLAN},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_1_START, WLBT_CBUS_BARAC_1_END, WLBT_USI_CHUB3},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_2_START, WLBT_CBUS_BARAC_2_END, WLBT_SYSREG_COMBINE_CHUB2WLBT},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_3_START, WLBT_CBUS_BARAC_3_END, WLBT_USI_CHUB0},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_4_START, WLBT_CBUS_BARAC_4_END, WLBT_GPIO_CHUB},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_5_START, WLBT_CBUS_BARAC_5_END, WLBT_GPIO_CMGP},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_6_START, WLBT_CBUS_BARAC_6_END, WLBT_SYSREG_CMGP2WLBT},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_7_START, WLBT_CBUS_BARAC_7_END, WLBT_USI_CMGP0},
	{BARAC_CTRL_VAL, WLBT_CBUS_BARAC_8_START, WLBT_CBUS_BARAC_8_END, WLBT_CHUB_SRAM},
};
