# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_SOC_S5E8855) += \
        s5e8855-erd8855.dtbo		\
        s5e8855-erd8855_16k.dtbo	\
        s5e8855-erd8855_emul.dtbo	\

always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
