# SPDX-License-Identifier: GPL-2.0
snd-soc-cs35l43-i2c-objs := cs35l43-i2c.o cs35l43.o cs35l43-tables.o
snd-soc-cs35l43-spi-objs := cs35l43-spi.o cs35l43.o cs35l43-tables.o

snd-soc-wm-adsp-objs := wm_adsp.o

obj-$(CONFIG_SND_SOC_CS35L43_I2C)	+= snd-soc-cs35l43-i2c.o
obj-$(CONFIG_SND_SOC_CS35L43_SPI)	+= snd-soc-cs35l43-spi.o

obj-$(CONFIG_SND_SOC_ABOX_WM_ADSP)	+= snd-soc-wm-adsp.o
