# SPDX-License-Identifier: GPL-2.0-only

# Memlogger
obj-$(CONFIG_EXYNOS_MEMORY_LOGGER)	+= memlogger.o

# Subsystem
obj-$(CONFIG_EXYNOS_SYSTEM_EVENT)	+= sysevent.o sysevent_notif.o

# Image Loader
obj-$(CONFIG_EXYNOS_IMGLOADER)		+= imgloader.o

# Exynos Chipid V2
obj-$(CONFIG_EXYNOS_CHIPID_V2)	+= exynos-chipid_v2.o

# Exynos USI V2
obj-$(CONFIG_EXYNOS_USI_V2)		+= exynos-usi_v2.o

obj-$(CONFIG_EXYNOS_PMU_IF)	+= exynos-pmu-if.o

# Exynos WoW
obj-$(CONFIG_EXYNOS_WOW)	+= exynos-wow.o

# Exynos MCINFO
obj-$(CONFIG_EXYNOS_MCINFO)             += exynos-mcinfo.o

# ICM(Exynos Isolated CryptoManager)
obj-$(CONFIG_EXYNOS_ICM)		+= exynos-icm.o

# Exynos Samsung Secure Platform
obj-$(CONFIG_EXYNOS_SSP)		+= exynos-ssp.o

# Secure log
obj-$(CONFIG_EXYNOS_SECURE_LOG)		+= exynos-seclog.o

# Exynos SEH
obj-$(CONFIG_EXYNOS_SEH)        	+= exynos-seh.o

# Exynos TZASC
obj-$(CONFIG_EXYNOS_TZASC_FAIL_DETECTOR) += exynos-tzasc.o

# secmem
obj-$(CONFIG_EXYNOS_CONTENT_PATH_PROTECTION) += secmem.o

# HDCP
obj-$(CONFIG_EXYNOS_HDCP2)		+= exynos-hdcp/

# SDM
obj-$(CONFIG_EXYNOS_SDM)		+= exynos-sdm.o

# HW RANDOM
obj-$(CONFIG_HW_RANDOM_EXYNOS_SWD)	+= exyswd-rng.o

# GCMA
obj-$(CONFIG_GCMA) += gcma/

# Memlogger Kunit test
obj-$(CONFIG_MEMLOGGER_EXYNOS_KUNIT_TEST)		+= test/
