// SPDX-License-Identifier: GPL-2.0
/*
 * Samsung Exynos SoC series Pablo IS driver
 *
 * Copyright (c) 2021 Samsung Electronics Co., Ltd
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef IS_HW_CSIS_V8_0_H
#define IS_HW_CSIS_V8_0_H

#include "pablo-hw-api-common.h"
#include "is-hw-api-csi.h"

/* DMA Format */
#define CSIS_REG_DMA_1D_DMA			(1)
#define CSIS_REG_DMA_2D_DMA			(0)
#define CSIS_REG_DMA_INPUT_OTF			(0)
#define CSIS_REG_DMA_INPUT_PRL			(1)

#define CSIS_DMA_FMT_U8BIT_PACK			(0x0)
#define CSIS_DMA_FMT_U8BIT_UNPACK_LSB_ZERO	(0x1)
#define CSIS_DMA_FMT_U8BIT_UNPACK_MSB_ZERO	(0x2)
#define CSIS_DMA_FMT_U10BIT_PACK		(0x4)
#define CSIS_DMA_FMT_U10BIT_UNPACK_LSB_ZERO	(0x5)
#define CSIS_DMA_FMT_U10BIT_UNPACK_MSB_ZERO	(0x6)
#define CSIS_DMA_FMT_ANDROID10			(0x7)
#define CSIS_DMA_FMT_U12BIT_PACK		(0x8)
#define CSIS_DMA_FMT_U12BIT_UNPACK_LSB_ZERO	(0x9)
#define CSIS_DMA_FMT_U12BIT_UNPACK_MSB_ZERO	(0xA)
#define CSIS_DMA_FMT_ANDROID12			(0xB)
#define CSIS_DMA_FMT_U14BIT_PACK		(0xC)
#define CSIS_DMA_FMT_U14BIT_UNPACK_LSB_ZERO	(0xD)
#define CSIS_DMA_FMT_U14BIT_UNPACK_MSB_ZERO	(0xE)

/*
 * 'b11 : Octa pixel mode (RAW8/10/12/14/16)
 * 'b10 : Quad pixel mode (RAW8/10/12/14/16/20)
 * 'b01 : Dual pixel mode (RAW8/10/12/14/16/20, YUV422, Compressed RAW6/7/8/10)
 * 'b00 : Single pixel mode
 */
#define CSIS_PIXEL_MODE_OCTA			(3)
#define CSIS_PIXEL_MODE_QUAD			(2)
#define CSIS_PIXEL_MODE_DUAL			(1)
#define CSIS_PIXEL_MODE_SING			(0)

#define CSIS_PARALLEL_MODE_OFF			(0)
#define CSIS_PARALLEL_MODE_32BIT		(1)
#define CSIS_PARALLEL_MODE_64BIT		(2)
#define CSIS_PARALLEL_MODE_128BIT		(3)

#define CSIS_IRQ_MASK0 0x01FFF1FF
#define CSIS_IRQ_MASK1 0x0000007F
#define CSIS_ERR_MASK0 0x01FFF1FF
#define CSIS_ERR_MASK1 0x00000078

#define CSIS_EBUF_IRQ_MASK0	0xF0
#define CSIS_EBUF_IRQ_MASK1	0xFF

/* FIXME: Move to DT or chip dependant file */
#define MAX_NUM_VOTF_VC (4) /* number of vc channel can support VOTF */

enum is_hw_csi_dma_int_src {
	CSIS_INT_DMA_LINE_END = 0,		/* [0] ~ [3] */
	CSIS_INT_DMA_FRAME_START = 4,		/* [4] ~ [7] */
	CSIS_INT_DMA_FRAME_END = 8,		/* [8] ~ [11] */
	CSIS_INT_DMA_FIFO_FULL = 12,
	CSIS_INT_DMA_ABORT_DONE = 13,
	CSIS_INT_DMA_LASTDATA_ERROR = 14,
	CSIS_INT_DMA_LASTADDR_ERROR = 15,
	CSIS_INT_DMA_FSTART_IN_FLUSH = 16,	/* [16] ~ [19] */
	CSIS_INT_DMA_OVERLAP = 20,		/* [20] ~ [23] */
	CSIS_INT_DMA_FRAME_DROP = 24,		/* [24] ~ [27] */
	CSIS_INT_DMA_C2COM_LOST_FLUSH = 28,	/* [28] ~ [31] */
};

#define CSIS_DMA_IRQ_MASK	((0)\
				/* |(1 << CSIS_INT_DMA_LINE_END) */\
				/* |(1 << (CSIS_INT_DMA_LINE_END + 1)) */\
				/* |(1 << (CSIS_INT_DMA_LINE_END + 2)) */\
				/* |(1 << (CSIS_INT_DMA_LINE_END + 3)) */\
				|(1 << CSIS_INT_DMA_FRAME_START)\
				|(1 << (CSIS_INT_DMA_FRAME_START + 1))\
				|(1 << (CSIS_INT_DMA_FRAME_START + 2))\
				|(1 << (CSIS_INT_DMA_FRAME_START + 3))\
				|(1 << CSIS_INT_DMA_FRAME_END)\
				|(1 << (CSIS_INT_DMA_FRAME_END + 1))\
				|(1 << (CSIS_INT_DMA_FRAME_END + 2))\
				|(1 << (CSIS_INT_DMA_FRAME_END + 3))\
				|(1 << CSIS_INT_DMA_FIFO_FULL)\
				|(1 << CSIS_INT_DMA_ABORT_DONE)\
				|(1 << CSIS_INT_DMA_LASTDATA_ERROR) \
				|(1 << CSIS_INT_DMA_LASTADDR_ERROR) \
				/* |(1 << CSIS_INT_DMA_FSTART_IN_FLUSH) */\
				/* |(1 << (CSIS_INT_DMA_FSTART_IN_FLUSH + 1)) */\
				/* |(1 << (CSIS_INT_DMA_FSTART_IN_FLUSH + 2)) */\
				/* |(1 << (CSIS_INT_DMA_FSTART_IN_FLUSH + 3)) */\
				|(1 << CSIS_INT_DMA_OVERLAP)\
				|(1 << (CSIS_INT_DMA_OVERLAP + 1))\
				|(1 << (CSIS_INT_DMA_OVERLAP + 2))\
				|(1 << (CSIS_INT_DMA_OVERLAP + 3))\
				/* |(1 << CSIS_INT_DMA_FRAME_DROP) */\
				/* |(1 << (CSIS_INT_DMA_FRAME_DROP + 1)) */\
				/* |(1 << (CSIS_INT_DMA_FRAME_DROP + 2)) */\
				/* |(1 << (CSIS_INT_DMA_FRAME_DROP + 3)) */\
				/* |(1 << CSIS_INT_DMA_C2COM_LOST_FLUSH) */\
				/* |(1 << (CSIS_INT_DMA_C2COM_LOST_FLUSH + 1)) */\
				/* |(1 << (CSIS_INT_DMA_C2COM_LOST_FLUSH + 2)) */\
				/* |(1 << (CSIS_INT_DMA_C2COM_LOST_FLUSH + 3)) */\
				)

/* CSI_LINK regs */
enum is_hw_csi_reg_name {
	/* COMMON */
	CSIS_R_CSIS_VERSION,
	CSIS_R_CSIS_CMN_CTRL,
	CSIS_R_CSIS_UPD_SDW,
	CSIS_R_CSIS_INT_MSK0,
	CSIS_R_CSIS_INT_SRC0,
	CSIS_R_CSIS_INT_MSK1,
	CSIS_R_CSIS_INT_SRC1,
	CSIS_R_FS_INT_MSK,
	CSIS_R_FS_INT_SRC,
	CSIS_R_FE_INT_MSK,
	CSIS_R_FE_INT_SRC,
	/* VC0 ~ VC9 */
	CSIS_R_ISP_CONFIG_CH0,
	CSIS_R_ISP_RESOL_CH0,
	CSIS_R_ISP_SYNC_CH0,
	CSIS_R_ISP_CONFIG_CH1,
	CSIS_R_ISP_RESOL_CH1,
	CSIS_R_ISP_SYNC_CH1,
	CSIS_R_ISP_CONFIG_CH2,
	CSIS_R_ISP_RESOL_CH2,
	CSIS_R_ISP_SYNC_CH2,
	CSIS_R_ISP_CONFIG_CH3,
	CSIS_R_ISP_RESOL_CH3,
	CSIS_R_ISP_SYNC_CH3,
	CSIS_R_ISP_CONFIG_CH4,
	CSIS_R_ISP_RESOL_CH4,
	CSIS_R_ISP_SYNC_CH4,
	CSIS_R_ISP_CONFIG_CH5,
	CSIS_R_ISP_RESOL_CH5,
	CSIS_R_ISP_SYNC_CH5,
	CSIS_R_ISP_CONFIG_CH6,
	CSIS_R_ISP_RESOL_CH6,
	CSIS_R_ISP_SYNC_CH6,
	CSIS_R_ISP_CONFIG_CH7,
	CSIS_R_ISP_RESOL_CH7,
	CSIS_R_ISP_SYNC_CH7,
	CSIS_R_ISP_CONFIG_CH8,
	CSIS_R_ISP_RESOL_CH8,
	CSIS_R_ISP_SYNC_CH8,
	CSIS_R_ISP_CONFIG_CH9,
	CSIS_R_ISP_RESOL_CH9,
	CSIS_R_ISP_SYNC_CH9,
	/* VC0 ~ VC9 */
	CSIS_R_SDW_CONFIG_CH0,
	CSIS_R_SDW_RESOL_CH0,
	CSIS_R_SDW_SYNC_CH0,
	CSIS_R_SDW_CONFIG_CH1,
	CSIS_R_SDW_RESOL_CH1,
	CSIS_R_SDW_SYNC_CH1,
	CSIS_R_SDW_CONFIG_CH2,
	CSIS_R_SDW_RESOL_CH2,
	CSIS_R_SDW_SYNC_CH2,
	CSIS_R_SDW_CONFIG_CH3,
	CSIS_R_SDW_RESOL_CH3,
	CSIS_R_SDW_SYNC_CH3,
	CSIS_R_SDW_CONFIG_CH4,
	CSIS_R_SDW_RESOL_CH4,
	CSIS_R_SDW_SYNC_CH4,
	CSIS_R_SDW_CONFIG_CH5,
	CSIS_R_SDW_RESOL_CH5,
	CSIS_R_SDW_SYNC_CH5,
	CSIS_R_SDW_CONFIG_CH6,
	CSIS_R_SDW_RESOL_CH6,
	CSIS_R_SDW_SYNC_CH6,
	CSIS_R_SDW_CONFIG_CH7,
	CSIS_R_SDW_RESOL_CH7,
	CSIS_R_SDW_SYNC_CH7,
	CSIS_R_SDW_CONFIG_CH8,
	CSIS_R_SDW_RESOL_CH8,
	CSIS_R_SDW_SYNC_CH8,
	CSIS_R_SDW_CONFIG_CH9,
	CSIS_R_SDW_RESOL_CH9,
	CSIS_R_SDW_SYNC_CH9,
	/* VC0 ~ VC9 */
	CSIS_R_FRM_CNT_CH0,
	CSIS_R_FRM_CNT_CH1,
	CSIS_R_FRM_CNT_CH2,
	CSIS_R_FRM_CNT_CH3,
	CSIS_R_FRM_CNT_CH4,
	CSIS_R_FRM_CNT_CH5,
	CSIS_R_FRM_CNT_CH6,
	CSIS_R_FRM_CNT_CH7,
	CSIS_R_FRM_CNT_CH8,
	CSIS_R_FRM_CNT_CH9,
	CSIS_R_LINE_INTR_CH0,
	CSIS_R_LINE_INTR_CH1,
	CSIS_R_LINE_INTR_CH2,
	CSIS_R_LINE_INTR_CH3,
	CSIS_R_LINE_INTR_CH4,
	CSIS_R_LINE_INTR_CH5,
	CSIS_R_LINE_INTR_CH6,
	CSIS_R_LINE_INTR_CH7,
	CSIS_R_LINE_INTR_CH8,
	CSIS_R_LINE_INTR_CH9,
	/* COMMON */
	CSIS_R_LRTE_CONFIG,
	CSIS_R_ERR_LOST_FS_MSK,
	CSIS_R_ERR_LOST_FS,
	CSIS_R_ERR_LOST_FE_MSK,
	CSIS_R_ERR_LOST_FE,
	CSIS_R_ERR_VRESOL_MSK,
	CSIS_R_ERR_VRESOL,
	CSIS_R_ERR_HRESOL_MSK,
	CSIS_R_ERR_HRESOL,
	CSIS_R_LINE_END_MSK,
	CSIS_R_LINE_END,
	CSIS_R_DBG_INTR_MSK,
	CSIS_R_DBG_INTR_SRC,
	CSIS_R_DBG_OPTION_SUITE,
	CSIS_R_DBG_PHASE_ONE_LANE0,
	CSIS_R_DBG_PHASE_ONE_LANE1,
	CSIS_R_DBG_PHASE_ONE_LANE2,
	CSIS_R_DBG_PHASE_TWO_LANE0,
	CSIS_R_DBG_PHASE_TWO_LANE1,
	CSIS_R_DBG_PHASE_TWO_LANE2,
	/* PHY */
	CSIS_R_PHY_STATUS,
	CSIS_R_PHY_CMN_CTRL,
	CSIS_REG_CNT,
};

static const struct is_reg csi_regs[CSIS_REG_CNT] = {
	/* COMMON */
	{0x0, "CSIS_VERSION"},
	{0x4, "CSIS_CMN_CTRL"},
	{0xC, "CSIS_UPD_SDW"},
	{0x10, "CSIS_INT_MSK0"},
	{0x14, "CSIS_INT_SRC0"},
	{0x18, "CSIS_INT_MSK1"},
	{0x1C, "CSIS_INT_SRC1"},
	{0x20, "FS_INT_MSK"},
	{0x24, "FS_INT_SRC"},
	{0x28, "FE_INT_MSK"},
	{0x2C, "FE_INT_SRC"},
	/* VC0 ~ VC9 */
	{0x40, "ISP_CONFIG_CH0"},
	{0x44, "ISP_RESOL_CH0"},
	{0x48, "ISP_SYNC_CH0"},
	{0x50, "ISP_CONFIG_CH1"},
	{0x54, "ISP_RESOL_CH1"},
	{0x58, "ISP_SYNC_CH1"},
	{0x60, "ISP_CONFIG_CH2"},
	{0x64, "ISP_RESOL_CH2"},
	{0x68, "ISP_SYNC_CH2"},
	{0x70, "ISP_CONFIG_CH3"},
	{0x74, "ISP_RESOL_CH3"},
	{0x78, "ISP_SYNC_CH3"},
	{0x80, "ISP_CONFIG_CH4"},
	{0x84, "ISP_RESOL_CH4"},
	{0x88, "ISP_SYNC_CH4"},
	{0x90, "ISP_CONFIG_CH5"},
	{0x94, "ISP_RESOL_CH5"},
	{0x98, "ISP_SYNC_CH5"},
	{0xA0, "ISP_CONFIG_CH6"},
	{0xA4, "ISP_RESOL_CH6"},
	{0xA8, "ISP_SYNC_CH6"},
	{0xB0, "ISP_CONFIG_CH7"},
	{0xB4, "ISP_RESOL_CH7"},
	{0xB8, "ISP_SYNC_CH7"},
	{0xC0, "ISP_CONFIG_CH8"},
	{0xC4, "ISP_RESOL_CH8"},
	{0xC8, "ISP_SYNC_CH8"},
	{0xD0, "ISP_CONFIG_CH9"},
	{0xD4, "ISP_RESOL_CH9"},
	{0xD8, "ISP_SYNC_CH9"},
	/* VC0 ~ VC9 */
	{0x240, "SDW_CONFIG_CH0"},
	{0x244, "SDW_RESOL_CH0"},
	{0x248, "SDW_SYNC_CH0"},
	{0x250, "SDW_CONFIG_CH1"},
	{0x254, "SDW_RESOL_CH1"},
	{0x258, "SDW_SYNC_CH1"},
	{0x260, "SDW_CONFIG_CH2"},
	{0x264, "SDW_RESOL_CH2"},
	{0x268, "SDW_SYNC_CH2"},
	{0x270, "SDW_CONFIG_CH3"},
	{0x274, "SDW_RESOL_CH3"},
	{0x278, "SDW_SYNC_CH3"},
	{0x280, "SDW_CONFIG_CH4"},
	{0x284, "SDW_RESOL_CH4"},
	{0x288, "SDW_SYNC_CH4"},
	{0x290, "SDW_CONFIG_CH5"},
	{0x294, "SDW_RESOL_CH5"},
	{0x298, "SDW_SYNC_CH5"},
	{0x2A0, "SDW_CONFIG_CH6"},
	{0x2A4, "SDW_RESOL_CH6"},
	{0x2A8, "SDW_SYNC_CH6"},
	{0x2B0, "SDW_CONFIG_CH7"},
	{0x2B4, "SDW_RESOL_CH7"},
	{0x2B8, "SDW_SYNC_CH7"},
	{0x2C0, "SDW_CONFIG_CH8"},
	{0x2C4, "SDW_RESOL_CH8"},
	{0x2C8, "SDW_SYNC_CH8"},
	{0x2D0, "SDW_CONFIG_CH9"},
	{0x2D4, "SDW_RESOL_CH9"},
	{0x2D8, "SDW_SYNC_CH9"},
	/* VC0 ~ VC9 */
	{0x500, "FRM_CNT_CH0"},
	{0x504, "FRM_CNT_CH1"},
	{0x508, "FRM_CNT_CH2"},
	{0x50C, "FRM_CNT_CH3"},
	{0x510, "FRM_CNT_CH4"},
	{0x514, "FRM_CNT_CH5"},
	{0x518, "FRM_CNT_CH6"},
	{0x51C, "FRM_CNT_CH7"},
	{0x520, "FRM_CNT_CH8"},
	{0x524, "FRM_CNT_CH9"},
	/* VC0 ~ VC9 */
	{0x580, "LINE_INTR_CH0"},
	{0x584, "LINE_INTR_CH1"},
	{0x588, "LINE_INTR_CH2"},
	{0x58c, "LINE_INTR_CH3"},
	{0x590, "LINE_INTR_CH4"},
	{0x594, "LINE_INTR_CH5"},
	{0x598, "LINE_INTR_CH6"},
	{0x59C, "LINE_INTR_CH7"},
	{0x5A0, "LINE_INTR_CH8"},
	{0x5A4, "LINE_INTR_CH9"},
	/* COMMON */
	{0x600, "LRTE_CONFIG"},
	{0x610, "ERR_LOST_FS_MSK"},
	{0x614, "ERR_LOST_FS"},
	{0x618, "ERR_LOST_FE_MSK"},
	{0x61C, "ERR_LOST_FE"},
	{0x620, "ERR_VRESOL_MSK"},
	{0x624, "ERR_VRESOL"},
	{0x628, "ERR_HRESOL_MSK"},
	{0x62C, "ERR_HRESOL"},
	{0x630, "LINE_END_MSK"},
	{0x634, "LINE_END"},
	{0x664, "DBG_INTR_MSK"},
	{0x668, "DBG_INTR_SRC"},
	{0x690, "DBG_OPTION_SUITE"},
	{0x6A0, "DBG_PHASE_ONE_LANE0"},
	{0x6A4, "DBG_PHASE_ONE_LANE1"},
	{0x6A8, "DBG_PHASE_ONE_LANE2"},
	{0x6AC, "DBG_PHASE_TWO_LANE0"},
	{0x6B0, "DBG_PHASE_TWO_LANE1"},
	{0x6B4, "DBG_PHASE_TWO_LANE2"},
	/* PHY */
	{0x700, "PHY_STATUS"},
	{0x704, "PHY_CMN_CTRL"},
};

enum is_hw_csi_reg_field {
	/* CSIS_VERSION */
	CSIS_F_MAJOR,
	CSIS_F_MINOR,
	CSIS_F_REVISION,
	CSIS_F_DERIVATIVE,
	/* CSIS_CMN_CTRL */
	CSIS_F_SROI_EN,
	CSIS_F_PHY_SEL,
	CSIS_F_QCHANNEL_EN,
	CSIS_F_DESKEW_LEVEL,
	CSIS_F_INTERLEAVE_MODE,
	CSIS_F_LANE_NUMBER,
	CSIS_F_DESCRAMBLE_EN,
	CSIS_F_UPDATE_SHADOW_CTRL,
	CSIS_F_SW_RESET,
	CSIS_F_CSI_EN,
	/* CSIS_UPD_SDW */
	CSIS_F_UPDATE_SHADOW,
	/* CSIS_INT_MSK0 */
	CSIS_F_MSK_PHY_TIMING_ERR,
	CSIS_F_MSK_ERRSOTSYNCHS,
	CSIS_F_MSK_ERR_SOT_HS,
	CSIS_F_MSK_RXINVALIDCODEHS,
	CSIS_F_MSK_DESKEW_OVER,
	CSIS_F_MSK_ERR_SKEW,
	CSIS_F_MSK_MAL_CRC,
	CSIS_F_MSK_ERR_CRC_PH,
	CSIS_F_MSK_ERR_OVER,
	CSIS_F_MSK_ERR_WRONG_CFG,
	CSIS_F_MSK_ERR_ECC,
	CSIS_F_MSK_ERR_CRC,
	CSIS_F_MSK_ERR_ID,
	/* CSIS_INT_SRC0 */
	CSIS_F_PHY_TIMING_ERR,
	CSIS_F_ERRSOTSYNCHS,
	CSIS_F_ERR_SOT_HS,
	CSIS_F_RXINVALIDCODEHS,
	CSIS_F_ERR_DESKEW_OVER,
	CSIS_F_ERR_SKEW,
	CSIS_F_MAL_CRC,
	CSIS_F_ERR_CRC_PH,
	CSIS_F_ERR_OVER,
	CSIS_F_ERR_WRONG_CFG,
	CSIS_F_ERR_ECC,
	CSIS_F_ERR_CRC,
	CSIS_F_ERR_ID,
	/* CSIS_INT_MSK1 */
	CSIS_F_MSK_VRESOL_MISMATCH,
	CSIS_F_MSK_HRESOL_MISMATCH,
	CSIS_F_MSK_ERR_LOST_FS,
	CSIS_F_MSK_ERR_LOST_FE,
	CSIS_F_MSK_FRAMESTART,
	CSIS_F_MSK_FRAMEEND,
	CSIS_F_MSK_LINE_END,
	/* CSIS_INT_SRC1 */
	CSIS_F_VRESOL_MISMATCH,
	CSIS_F_HRESOL_MISMATCH,
	CSIS_F_ERR_LOST_FS,
	CSIS_F_ERR_LOST_FE,
	CSIS_F_FRAMESTART,
	CSIS_F_FRAMEEND,
	CSIS_F_LINE_END,
	/* FS_INT_MSK */
	CSIS_F_MSK_FRAMESTART_CH,
	/* FS_INT_SRC */
	CSIS_F_FRAMESTART_CH,
	/* FE_INT_MSK */
	CSIS_F_MSK_FRAMEEND_CH,
	/* FE_INT_SRC */
	CSIS_F_FRAMEEND_CH,
	/* ISP_CONFIG_CHX */
	CSIS_F_VIRTUAL_CHANNEL,
	CSIS_F_PARALLEL_MODE,
	CSIS_F_PIXEL_MODE,
	CSIS_F_RGB_SWAP,
	CSIS_F_DECOMP_PREDICT,
	CSIS_F_DECOMP_EN,
	CSIS_F_DATAFORMAT,
	/* ISP_RESOL_CHX */
	CSIS_F_VRESOL,
	CSIS_F_HRESOL,
	/* ISP_SYNC_CHX */
	CSIS_F_HSYNC_LINTV,
	/* SDW_CONFIG_CHX */
	CSIS_F_VIRTUAL_CHANNEL_SDW,
	CSIS_F_PARALLEL_MODE_SDW,
	CSIS_F_PIXEL_MODE_SDW,
	CSIS_F_RGB_SWAP_SDW,
	CSIS_F_DECOMP_PREDICT_SDW,
	CSIS_F_DECOMP_EN_SDW,
	CSIS_F_DATAFORMAT_SDW,
	/* SDW_RESOL_CHX */
	CSIS_F_VRESOL_SDW,
	CSIS_F_HRESOL_SDW,
	/* SDW_SYNC_CHX */
	CSIS_F_HSYNC_LINTV_SDW,
	/* FRM_CNT_CHX */
	CSIS_F_FRM_CNT_CHX,
	/* LINE_INTR_CHX */
	CSIS_F_LINE_INTR_CHX,
	/* LRTE_CONFIG */
	CSIS_F_EPD_EN,
	CSIS_F_EPD_SP_SPACERS,
	CSIS_F_D_PHY_EPD_OPTION,
	CSIS_F_EPD_LP_SPACERS,
	/* ERR_LOST_FS_MSK */
	CSIS_F_MSK_ERR_LOST_FS_CH,
	/* ERR_LOST_FS */
	CSIS_F_ERR_LOST_FS_CH,
	/* ERR_LOST_FE_MSK */
	CSIS_F_MSK_ERR_LOST_FE_CH,
	/* ERR_LOST_FE */
	CSIS_F_ERR_LOST_FE_CH,
	/* ERR_VRESOL_MSK */
	CSIS_F_MSK_VRESOL_MISMATCH_CH,
	/* ERR_VRESOL */
	CSIS_F_VRESOL_MISMATCH_CH,
	/* ERR_HRESOL_MSK */
	CSIS_F_MSK_HRESOL_MISMATCH_CH,
	/* ERR_HRESOL */
	CSIS_F_HRESOL_MISMATCH_CH,
	/* LINE_END_MSK */
	CSIS_F_MSK_LINE_END_CH,
	/* LINE_END */
	CSIS_F_LINE_END_CH,
	/* DBG_OPTION_SUITE */
	CSIS_F_DBG_EPD_OPT2_NO_EOTP,
	CSIS_F_DBG_PIXEL_ALIGN_EN,
	/* PHY_STATUS */
	CSIS_F_ULPSDAT,
	CSIS_F_STOPSTATEDAT,
	CSIS_F_ULPSCLK,
	CSIS_F_STOPSTATECLK,
	/* PHY_CMN_CTRL */
	CSIS_F_ENABLE_DAT,
	CSIS_F_ENABLE_CLK,
	CSIS_REG_FIELD_CNT
};

static const struct is_field csi_fields[CSIS_REG_FIELD_CNT] = {
	/* filed_name, start_bit, bit_width, type, reset */
	/* CSIS_VERSION */
	{"MAJOR", 24, 8, RWI, 0x8},
	{"MINOR", 16, 8, RWI, 0x0},
	{"REVISION", 8, 8, RWI, 0x0},
	{"DERIVATIVE", 0, 8, RWI, 0x0},
	/* CSIS_CMN_CTRL */
	{"SROI_EN", 22, 1, RW, 0x0},
	{"PHY_SEL", 21, 1, RW, 0x0},
	{"QCHANNEL_EN", 20, 1, RW, 0x0},
	{"DESKEW_LEVEL", 12, 4, RW, 0x2},
	{"INTERLEAVE_MODE", 10, 2, RW, 0x0},
	{"LANE_NUMBER", 8, 2, RW, 0x0},
	{"DESCRAMBLE_EN", 3, 1, RW, 0x0},
	{"UPDATE_SHADOW_CTRL", 2, 1, RW, 0x0},
	{"SW_RESET", 1, 1, RIW, 0x0},
	{"CSI_EN", 0, 1, RW, 0x0},
	/* CSIS_UPD_SDW */
	{"UPDATE_SHADOW", 0, 32, RW, 0x0},
	/* CSIS_INT_MSK0 */
	{"MSK_PHY_TIMING_ERR", 24, 1, RW, 0x0},
	{"MSK_ERRSOTSYNCHS", 20, 4, RW, 0x0},
	{"MSK_ERR_SOT_HS", 16, 4, RW, 0x0},
	{"MSK_RXINVALIDCODEHS", 12, 4, RW, 0x0},
	{"MSK_ERR_DESKEW_OVER", 8, 1, RW, 0x0},
	{"MSK_ERR_SKEW", 7, 1, RW, 0x0},
	{"MSK_MAL_CRC", 6, 1, RW, 0x0},
	{"MSK_ERR_CRC_PH", 5, 1, RW, 0x0},
	{"MSK_ERR_OVER", 4, 1, RW, 0x0},
	{"MSK_ERR_WRONG_CFG", 3, 1, RW, 0x0},
	{"MSK_ERR_ECC", 2, 1, RW, 0x0},
	{"MSK_ERR_CRC", 1, 1, RW, 0x0},
	{"MSK_ERR_ID", 0, 1, RW, 0x0},
	/* CSIS_INT_SRC0 */
	{"PHY_TIMING_ERR", 24, 1, RWC, 0x0},
	{"ERRSOTSYNCHS", 20, 4, RWC, 0x0},
	{"ERR_SOT_HS", 16, 4, RWC, 0x0},
	{"RXINVALIDCODEHS", 12, 4, RWC, 0x0},
	{"ERR_DESKEW_OVER", 8, 1, RW, 0x0},
	{"ERR_SKEW", 7, 1, RW, 0x0},
	{"MAL_CRC", 6, 1, RWC, 0x0},
	{"ERR_CRC_PH", 5, 1, RWC, 0x0},
	{"ERR_OVER", 4, 1, RWC, 0x0},
	{"ERR_WRONG_CFG", 3, 1, RWC, 0x0},
	{"ERR_ECC", 2, 1, RWC, 0x0},
	{"ERR_CRC", 1, 1, RWC, 0x0},
	{"ERR_ID", 0, 1, RWC, 0x0},
	/* CSIS_INT_MSK1 */
	{"MSK_VRESOL_MISMATCH", 6, 1, RW, 0x0},
	{"MSK_HRESOL_MISMATCH", 5, 1, RW, 0x0},
	{"MSK_ERR_LOST_FS", 4, 1, RW, 0x0},
	{"MSK_ERR_LOST_FE", 3, 1, RW, 0x0},
	{"MSK_FRAMESTART", 2, 1, RW, 0x0},
	{"MSK_FRAMEEND", 1, 1, RW, 0x0},
	{"MSK_LINE_END", 0, 1, RW, 0x0},
	/* CSIS_INT_SRC1 */
	{"VRESOL_MISMATCH", 6, 1, RWC, 0x0},
	{"HRESOL_MISMATCH", 5, 1, RWC, 0x0},
	{"ERR_LOST_FS", 4, 1, RWC, 0x0},
	{"ERR_LOST_FE", 3, 1, RWC, 0x0},
	{"FRAMESTART", 2, 1, RWC, 0x0},
	{"FRAMEEND", 1, 1, RWC, 0x0},
	{"LINE_END", 0, 1, RWC, 0x0},
	/* FS_INT_MSK */
	{"MSK_FRAMESTART_CH", 0, 32, RW, 0xFFFFFFFF},
	/* FS_INT_SRC */
	{"FRAMESTART_CH", 0, 32, RWC, 0x0},
	/* FE_INT_MSK */
	{"MSK_FRAMEEND_CH", 0, 32, RW, 0xFFFFFFFF},
	/* FE_INT_SRC */
	{"FRAMEEND_CH", 0, 32, RWC, 0x0},
	/* ISP_CONFIG_CHX */
	{"VIRTUAL_CHANNEL", 16, 5, RW, 0x0},
	{"PARALLEL_MODE", 14, 2, RW, 0x0},
	{"PIXEL_MODE", 12, 2, RW, 0x0},
	{"RGB_SWAP", 10, 1, RW, 0x0},
	{"DECOMP_PREDICT", 9, 1, RW, 0x0},
	{"DECOMP_EN", 8, 1, RW, 0x0},
	{"DATAFORMAT", 2, 6, RW, 0x3F},
	/* ISP_RESOL_CHX */
	{"VRESOL", 16, 16, RW, 0x8000},
	{"HRESOL", 0, 16, RW, 0x8000},
	/* ISP_SYNC_CHX */
	{"HSYNC_LINTV", 18, 6, RW, 0x0},
	/* SDW_CONFIG_CHX */
	{"VIRTUAL_CHANNEL_SDW", 16, 5, RWI, 0x0},
	{"PARALLEL_MODE_SDW", 14, 2, RWI, 0x0},
	{"PIXEL_MODE_SDW", 12, 2, RWI, 0x0},
	{"RGB_SWAP_SDW", 10, 1, RWI, 0x0},
	{"DECOMP_PREDICT_SDW", 9, 1, RWI, 0x0},
	{"DECOMP_EN_SDW", 8, 1, RWI, 0x0},
	{"DATAFORMAT_SDW", 2, 6, RWI, 0x3F},
	/* SDW_RESOL_CHX */
	{"VRESOL_SDW", 16, 16, RWI, 0x8000},
	{"HRESOL_SDW", 0, 16, RWI, 0x8000},
	/* SDW_SYNC_CHX */
	{"HSYNC_LINTV_SDW", 18, 6, RWI, 0x0},
	/* FRM_CNT_CHX */
	{"FRM_CNT_CHX", 0, 32, RW, 0x0},
	/* LINE_INTR_CHX */
	{"LINE_INTR_CHX", 0, 32, RW, 0x0},
	/* LRTE_CONFIG */
	{"EPD_EN", 31, 1, RW, 0x0},
	{"EPD_SP_SPACERS", 16, 15, RW, 0x7FFF},
	{"D_PHY_EPD_OPTION", 15, 1, RW, 0x0},
	{"EPD_LP_SPACERS", 0, 15, RW, 0x7FFF},
	/* ERR_LOST_FS_MSK */
	{"MSK_ERR_LOST_FS_CH", 0, 32, RW, 0xFFFFFFFF},
	/* ERR_LOST_FS */
	{"ERR_LOST_FS_CH", 0, 32, RWC, 0x0},
	/* ERR_LOST_FE_MSK */
	{"MSK_ERR_LOST_FE_CH", 0, 32, RW, 0xFFFFFFFF},
	/* ERR_LOST_FE */
	{"ERR_LOST_FE_CH", 0, 32, RWC, 0x0},
	/* ERR_VRESOL_MSK */
	{"MSK_VRESOL_MISMATCH_CH", 0, 32, RW, 0xFFFFFFFF},
	/* ERR_VRESOL */
	{"VRESOL_MISMATCH_CH", 0, 32, RWC, 0x0},
	/* ERR_HRESOL_MSK */
	{"MSK_HRESOL_MISMATCH_CH", 0, 32, RW, 0xFFFFFFFF},
	/* ERR_HRESOL */
	{"HRESOL_MISMATCH_CH", 0, 32, RWC, 0x0},
	/* LINE_END_MSK */
	{"MSK_LINE_END_CH", 0, 32, RW, 0xFFFFFFFF},
	/* LINE_END */
	{"LINE_END_CH", 0, 32, RWC, 0x0},
	/* DBG_OPTION_SUITE */
	{"DBG_EPD_OPT2_NO_EOTP", 28, 1, RW, 0x0},
	{"DBG_PIXEL_ALIGN_EN", 23, 1, RW, 0x0},
	/* PHY_STATUS */
	{"ULPSDAT", 8, 4, RWI, 0x0},
	{"STOPSTATEDAT", 4, 4, RWI, 0xF},
	{"ULPSCLK", 1, 1, RWI, 0x0},
	{"STOPSTATECLK", 0, 1, RWI, 0x1},
	/* PHY_CMN_CTRL */
	{"ENABLE_DAT", 1, 4, RW, 0x0},
	{"ENABLE_CLK", 0, 1, RW, 0x0},
};

/* CSIS_DMA_COMMON regs */
enum is_hw_csi_dma_cmn_reg_name {
	CSIS_DMA_CMN_R_CSIS_CMN_DMA_CTRL,
	CSIS_DMA_CMN_R_CSIS_CMN_DMA_CLK_CTRL,
	CSIS_DMA_CMN_R_CSIS_CMN_TEST_PATTERN_ON,
	CSIS_DMA_CMN_R_CSIS_CMN_TEST_PATTERN_CTRL,
	CSIS_DMA_CMN_R_CSIS_CMN_TEST_PATTERN_SIZE,
	CSIS_DMA_CMN_R_CSIS_CMN_DMA_CFG_CSIS0,
	CSIS_DMA_CMN_R_CSIS_CMN_DMA_CFG_CSIS1,
	CSIS_DMA_CMN_R_CSIS_CMN_DMA_CFG_CSIS2,
	CSIS_DMA_CMN_R_CSIS_CMN_DMA_CFG_CSIS3,
	CSIS_DMA_CMN_R_CSIS_CMN_DMA_CFG_CSIS4,
	CSIS_DMA_CMN_R_CSIS_CMN_SBWC_SEL,
	CSIS_DMA_CMN_R_CSIS_CMN_SBWC_TURN_CNT,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_CSIS_MODE,
	CSIS_DMA_CMN_R_CSIS_CMN_CUE_FLAG,
	CSIS_DMA_CMN_R_CSIS_CMN_CUE_FRAME_PTR,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY0,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY1,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY2,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY3,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY4,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY5,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY6,
	CSIS_DMA_CMN_R_CSIS_CMN_SECURITY7,
	CSIS_DMA_CMN_R_CSIS_CMN_QURGENT_EN,
	CSIS_DMA_CMN_R_CSIS_CMN_VOTF_CFG,
	CSIS_DMA_CMN_R_CSIS_CMN_OVERFLOW_INT_ENABLE,
	CSIS_DMA_CMN_R_CSIS_CMN_OVERFLOW_INT_SRC,
	CSIS_DMA_CMN_R_CSIS_CMN_OVERFLOW_DBG_INFO0,
	CSIS_DMA_CMN_R_CSIS_CMN_OVERFLOW_DBG_INFO1,
	CSIS_DMA_CMN_R_CSIS_CMN_OVERFLOW_DBG_INFO2,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_CUR_FRAME_ID0,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_CUR_FRAME_ID1,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_CUR_FRAME_ID2,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_CUR_FRAME_ID3,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_PREV_FRAME_ID0,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_PREV_FRAME_ID1,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_PREV_FRAME_ID2,
	CSIS_DMA_CMN_R_CSIS_CMN_FRO_PREV_FRAME_ID3,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_EN,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH0_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH1_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH2_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH3_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH0_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH1_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH2_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS0_CH3_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH0_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH1_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH2_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH3_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH0_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH1_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH2_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS1_CH3_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH0_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH1_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH2_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH3_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH0_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH1_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH2_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS2_CH3_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH0_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH1_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH2_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH3_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH0_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH1_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH2_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS3_CH3_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH0_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH1_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH2_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH3_VCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH0_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH1_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH2_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_CSIS4_CH3_HDCNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_40,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_41,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_42,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_43,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_44,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_45,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_46,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_INFO_47,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_DBG_CNT,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M0,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M1,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M2,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M3,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M4,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M5,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M6,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M7,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M8,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M9,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M10,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M11,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M0,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M1,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M2,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M3,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M4,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M5,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M6,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M7,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M8,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M9,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M10,
	CSIS_DMA_CMN_R_CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M11,
	CSIS_DMA_CMN_REG_CNT
};

static const struct is_reg csi_dma_cmn_regs[CSIS_DMA_CMN_REG_CNT] = {
	{0x0008, "CSIS_CMN_DMA_CTRL"},
	{0x0014, "CSIS_CMN_DMA_CLK_CTRL"},
	{0x0020, "CSIS_CMN_TEST_PATTERN_ON"},
	{0x0024, "CSIS_CMN_TEST_PATTERN_CTRL"},
	{0x0028, "CSIS_CMN_TEST_PATTERN_SIZE"},
	{0x002C, "CSIS_CMN_DMA_CFG_CSIS0"},
	{0x0030, "CSIS_CMN_DMA_CFG_CSIS1"},
	{0x0034, "CSIS_CMN_DMA_CFG_CSIS2"},
	{0x0038, "CSIS_CMN_DMA_CFG_CSIS3"},
	{0x003C, "CSIS_CMN_DMA_CFG_CSIS4"},
	{0x0050, "CSIS_CMN_SBWC_SEL"},
	{0x0054, "CSIS_CMN_SBWC_TURN_CNT"},
	{0x0060, "CSIS_CMN_FRO_CSIS_MODE"},
	{0x0064, "CSIS_CMN_CUE_FLAG"},
	{0x0068, "CSIS_CMN_CUE_FRAME_PTR"},
	{0x0080, "CSIS_CMN_SECURITY0"},
	{0x0084, "CSIS_CMN_SECURITY1"},
	{0x0088, "CSIS_CMN_SECURITY2"},
	{0x008C, "CSIS_CMN_SECURITY3"},
	{0x0090, "CSIS_CMN_SECURITY4"},
	{0x0094, "CSIS_CMN_SECURITY5"},
	{0x0098, "CSIS_CMN_SECURITY6"},
	{0x009C, "CSIS_CMN_SECURITY7"},
	{0x00A0, "CSIS_CMN_QURGENT_EN"},
	{0x00A4, "CSIS_CMN_VOTF_CFG"},
	{0x00A8, "CSIS_CMN_OVERFLOW_INT_ENABLE"},
	{0x00AC, "CSIS_CMN_OVERFLOW_INT_SRC"},
	{0x00B0, "CSIS_CMN_OVERFLOW_DBG_INFO0"},
	{0x00B4, "CSIS_CMN_OVERFLOW_DBG_INFO1"},
	{0x00B8, "CSIS_CMN_OVERFLOW_DBG_INFO2"},
	{0x00E0, "CSIS_CMN_FRO_CUR_FRAME_ID0"},
	{0x00E4, "CSIS_CMN_FRO_CUR_FRAME_ID1"},
	{0x00E8, "CSIS_CMN_FRO_CUR_FRAME_ID2"},
	{0x00EC, "CSIS_CMN_FRO_CUR_FRAME_ID3"},
	{0x00F0, "CSIS_CMN_FRO_PREV_FRAME_ID0"},
	{0x00F4, "CSIS_CMN_FRO_PREV_FRAME_ID1"},
	{0x00F8, "CSIS_CMN_FRO_PREV_FRAME_ID2"},
	{0x00FC, "CSIS_CMN_FRO_PREV_FRAME_ID3"},
	{0x0100, "CSIS_CMN_DEBUG_EN"},
	{0x0104, "CSIS_CMN_DEBUG_INFO_CSIS0_CH0_VCNT"},
	{0x0108, "CSIS_CMN_DEBUG_INFO_CSIS0_CH1_VCNT"},
	{0x010C, "CSIS_CMN_DEBUG_INFO_CSIS0_CH2_VCNT"},
	{0x0110, "CSIS_CMN_DEBUG_INFO_CSIS0_CH3_VCNT"},
	{0x0114, "CSIS_CMN_DEBUG_INFO_CSIS0_CH0_HDCNT"},
	{0x0118, "CSIS_CMN_DEBUG_INFO_CSIS0_CH1_HDCNT"},
	{0x011C, "CSIS_CMN_DEBUG_INFO_CSIS0_CH2_HDCNT"},
	{0x0120, "CSIS_CMN_DEBUG_INFO_CSIS0_CH3_HDCNT"},
	{0x0124, "CSIS_CMN_DEBUG_INFO_CSIS1_CH0_VCNT"},
	{0x0128, "CSIS_CMN_DEBUG_INFO_CSIS1_CH1_VCNT"},
	{0x012C, "CSIS_CMN_DEBUG_INFO_CSIS1_CH2_VCNT"},
	{0x0130, "CSIS_CMN_DEBUG_INFO_CSIS1_CH3_VCNT"},
	{0x0134, "CSIS_CMN_DEBUG_INFO_CSIS1_CH0_HDCNT"},
	{0x0138, "CSIS_CMN_DEBUG_INFO_CSIS1_CH1_HDCNT"},
	{0x013C, "CSIS_CMN_DEBUG_INFO_CSIS1_CH2_HDCNT"},
	{0x0140, "CSIS_CMN_DEBUG_INFO_CSIS1_CH3_HDCNT"},
	{0x0144, "CSIS_CMN_DEBUG_INFO_CSIS2_CH0_VCNT"},
	{0x0148, "CSIS_CMN_DEBUG_INFO_CSIS2_CH1_VCNT"},
	{0x014C, "CSIS_CMN_DEBUG_INFO_CSIS2_CH2_VCNT"},
	{0x0150, "CSIS_CMN_DEBUG_INFO_CSIS2_CH3_VCNT"},
	{0x0154, "CSIS_CMN_DEBUG_INFO_CSIS2_CH0_HDCNT"},
	{0x0158, "CSIS_CMN_DEBUG_INFO_CSIS2_CH1_HDCNT"},
	{0x015C, "CSIS_CMN_DEBUG_INFO_CSIS2_CH2_HDCNT"},
	{0x0160, "CSIS_CMN_DEBUG_INFO_CSIS2_CH3_HDCNT"},
	{0x0164, "CSIS_CMN_DEBUG_INFO_CSIS3_CH0_VCNT"},
	{0x0168, "CSIS_CMN_DEBUG_INFO_CSIS3_CH1_VCNT"},
	{0x016C, "CSIS_CMN_DEBUG_INFO_CSIS3_CH2_VCNT"},
	{0x0170, "CSIS_CMN_DEBUG_INFO_CSIS3_CH3_VCNT"},
	{0x0174, "CSIS_CMN_DEBUG_INFO_CSIS3_CH0_HDCNT"},
	{0x0178, "CSIS_CMN_DEBUG_INFO_CSIS3_CH1_HDCNT"},
	{0x017C, "CSIS_CMN_DEBUG_INFO_CSIS3_CH2_HDCNT"},
	{0x0180, "CSIS_CMN_DEBUG_INFO_CSIS3_CH3_HDCNT"},
	{0x0184, "CSIS_CMN_DEBUG_INFO_CSIS4_CH0_VCNT"},
	{0x0188, "CSIS_CMN_DEBUG_INFO_CSIS4_CH1_VCNT"},
	{0x018C, "CSIS_CMN_DEBUG_INFO_CSIS4_CH2_VCNT"},
	{0x0190, "CSIS_CMN_DEBUG_INFO_CSIS4_CH3_VCNT"},
	{0x0194, "CSIS_CMN_DEBUG_INFO_CSIS4_CH0_HDCNT"},
	{0x0198, "CSIS_CMN_DEBUG_INFO_CSIS4_CH1_HDCNT"},
	{0x019C, "CSIS_CMN_DEBUG_INFO_CSIS4_CH2_HDCNT"},
	{0x01A0, "CSIS_CMN_DEBUG_INFO_CSIS4_CH3_HDCNT"},
	{0x01A4, "CSIS_CMN_DEBUG_INFO_40"},
	{0x01A8, "CSIS_CMN_DEBUG_INFO_41"},
	{0x01AC, "CSIS_CMN_DEBUG_INFO_42"},
	{0x01B0, "CSIS_CMN_DEBUG_INFO_43"},
	{0x01B4, "CSIS_CMN_DEBUG_INFO_44"},
	{0x01B8, "CSIS_CMN_DEBUG_INFO_45"},
	{0x01BC, "CSIS_CMN_DEBUG_INFO_46"},
	{0x01C0, "CSIS_CMN_DEBUG_INFO_47"},
	{0x01C4, "CSIS_CMN_DEBUG_INFO_AXI_DBG_CNT"},
	{0x01C8, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M0"},
	{0x01CC, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M1"},
	{0x01D0, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M2"},
	{0x01D4, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M3"},
	{0x01D8, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M4"},
	{0x01DC, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M5"},
	{0x01E0, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M6"},
	{0x01E4, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M7"},
	{0x01E8, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M8"},
	{0x01EC, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M9"},
	{0x01F0, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M10"},
	{0x01F4, "CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_M11"},
	{0x01F8, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M0"},
	{0x01FC, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M1"},
	{0x0200, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M2"},
	{0x0204, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M3"},
	{0x0208, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M4"},
	{0x020C, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M5"},
	{0x0210, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M6"},
	{0x0214, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M7"},
	{0x0218, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M8"},
	{0x021C, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M9"},
	{0x0220, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M10"},
	{0x0224, "CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_M11"},
};

enum is_hw_csi_dma_cmn_reg_field {
	/* CSIS_CMN_DMA_CTRL */
	CSIS_DMA_CMN_F_CORE_RESET,
	CSIS_DMA_CMN_F_IP_PROCESSING,
	CSIS_DMA_CMN_F_SW_RESET,
	/* CSIS_CMN_DMA_CLK_CTRL */
	CSIS_DMA_CMN_F_CLKGATE_OFF,
	/* CSIS_CMN_TEST_PATTERN_ON */
	CSIS_DMA_CMN_F_TESTPATTERN,
	CSIS_DMA_CMN_F_PPCMODE,
	CSIS_DMA_CMN_F_VBLANK,
	/* CSIS_CMN_TEST_PATTERN_CTRL */
	CSIS_DMA_CMN_F_VTOHBLANK,
	CSIS_DMA_CMN_F_HBLANK,
	CSIS_DMA_CMN_F_HTOVBLANK,
	/* CSIS_CMN_TEST_PATTERN_SIZE */
	CSIS_DMA_CMN_F_TP_VSIZE,
	CSIS_DMA_CMN_F_TP_HSIZE,
	/* CSIS_CMN_DMA_CFG_CSISX */
	CSIS_DMA_CMN_F_AUTO_FLUSH_EN,
	CSIS_DMA_CMN_F_MAX_16BL,
	CSIS_DMA_CMN_F_BUSINFO,
	CSIS_DMA_CMN_F_VOTF_EN_CH3,
	CSIS_DMA_CMN_F_VOTF_EN_CH2,
	CSIS_DMA_CMN_F_VOTF_EN_CH1,
	CSIS_DMA_CMN_F_VOTF_EN_CH0,
	CSIS_DMA_CMN_F_VOTF_STALL_EN,
	CSIS_DMA_CMN_F_CSIS_WDMA_CLK_ALWAYS_ON,
	CSIS_DMA_CMN_F_MAX_MO,
	/* CSIS_CMN_SBWC_SEL */
	CSIS_DMA_CMN_F_SBWC_SEL_F7,
	CSIS_DMA_CMN_F_SBWC_SEL_F6,
	CSIS_DMA_CMN_F_SBWC_SEL_F5,
	CSIS_DMA_CMN_F_SBWC_SEL_F4,
	CSIS_DMA_CMN_F_SBWC_SEL_F3,
	CSIS_DMA_CMN_F_SBWC_SEL_F2,
	CSIS_DMA_CMN_F_SBWC_SEL_F1,
	CSIS_DMA_CMN_F_SBWC_SEL_F0,
	/* CSIS_CMN_SBWC_TURN_CNT */
	CSIS_DMA_CMN_F_CSIS_CMN_SBWC_TURN,
	CSIS_DMA_CMN_F_CSIS_CMN_SBWC_TURN_CNT_CLEAR,
	/* CSIS_CMN_FRO_CSIS_MODE */
	CSIS_DMA_CMN_F_FRO_CSIS_SEL,
	CSIS_DMA_CMN_F_FRO_CSIS_MODE,
	/* CSIS_CMN_CUE_FLAG */
	CSIS_DMA_CMN_F_FRO_CUE_FLAG_SET,
	/* CSIS_CMN_CUE_FRAME_PTR */
	CSIS_DMA_CMN_F_CUE_FRAME_PTR_CH3,
	CSIS_DMA_CMN_F_CUE_FRAME_PTR_CH2,
	CSIS_DMA_CMN_F_CUE_FRAME_PTR_CH1,
	CSIS_DMA_CMN_F_CUE_FRAME_PTR_CH0,
	/* CSIS_CMN_SECURITYX */
	CSIS_DMA_CMN_F_SEQIDX_SECURITY,
	/* CSIS_CMN_QURGENT_EN */
	CSIS_DMA_CMN_F_EBUF_QURGENT_EN,
	CSIS_DMA_CMN_F_DMA_QURGENT_EN,
	/* CSIS_CMN_VOTF_CFG */
	CSIS_DMA_CMN_F_VOTF_USE_LEGACY_RING,
	/* CSIS_CMN_OVERFLOW_INT_SRC */
	CSIS_DMA_CMN_F_INT_ENABLE,
	/* CSIS_CMN_OVERFLOW_INT_SRC */
	CSIS_DMA_CMN_F_INT_SRC,
	/* CSIS_CMN_OVERFLOW_DBG_INFOX */
	CSIS_DMA_CMN_F_DBG_INFOX,
	/* CSIS_CMN_FRO_CUR_FRAME_ID0 */
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID7,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID6,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID5,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID4,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID3,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID2,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID1,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID0,
	/* CSIS_CMN_FRO_CUR_FRAME_ID1 */
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID15,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID14,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID13,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID12,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID11,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID10,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID9,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID8,
	/* CSIS_CMN_FRO_CUR_FRAME_ID2 */
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID23,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID22,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID21,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID20,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID19,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID18,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID17,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID16,
	/* CSIS_CMN_FRO_CUR_FRAME_ID3 */
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID31,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID30,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID29,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID28,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID27,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID26,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID25,
	CSIS_DMA_CMN_F_FRO_CUR_FRAME_ID24,
	/* CSIS_CMN_FRO_PREV_FRAME_ID0 */
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID7,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID6,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID5,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID4,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID3,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID2,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID1,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID0,
	/* CSIS_CMN_FRO_PREV_FRAME_ID1 */
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID15,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID14,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID13,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID12,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID11,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID10,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID9,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID8,
	/* CSIS_CMN_FRO_PREV_FRAME_ID2 */
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID23,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID22,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID21,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID20,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID19,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID18,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID17,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID16,
	/* CSIS_CMN_FRO_PREV_FRAME_ID3 */
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID31,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID30,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID29,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID28,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID27,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID26,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID25,
	CSIS_DMA_CMN_F_FRO_PREV_FRAME_ID24,
	/* CSIS_CMN_DEBUG_EN */
	CSIS_DMA_CMN_F_DMA_CAPTURE_ONCE,
	CSIS_DMA_CMN_F_DMA_DEBUG_ENABLE,
	/* CSIS_CMN_DEBUG_INFO_CSISX_CHX_VCNT */
	CSIS_DMA_CMN_F_DMAX_CHX_VCNT,
	/* CSIS_CMN_DEBUG_INFO_CSISX_CHX_HDCNT */
	CSIS_DMA_CMN_F_DMAX_CHX_HDCNT,
	/* CSIS_CMN_DEBUG_INFO_AXI_DBG_CNT */
	CSIS_DMA_CMN_F_AXI_DBG_CNT,
	/* CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_MX */
	CSIS_DMA_CMN_F_AXI_BLK_CNT_MX,
	/* CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_MX */
	CSIS_DMA_CMN_F_AXI_MO_CNT_MX,
	CSIS_DMA_CMN_REG_FIELD_CNT
};

static const struct is_field csi_dma_cmn_fields[CSIS_DMA_CMN_REG_FIELD_CNT] = {
	/* CSIS_CMN_DMA_CTRL */
	{"CORE_RESET", 3, 1, RW, 0x0},
	{"IP_PROCESSING", 1, 1, RW, 0x0},
	{"SW_RESET", 0, 1, RW, 0x0},
	/* CSIS_CMN_DMA_CLK_CTRL */
	{"CLKGATE_OFF", 0, 1, RW, 0x0},
	/* CSIS_CMN_TEST_PATTERN_ON */
	{"TESTPATTERN", 31, 1, RW, 0x0},
	{"PPCMODE", 30, 1, RW, 0x1},
	{"VBLANK", 0, 30, RW, 0x3fff},
	/* CSIS_CMN_TEST_PATTERN_CTRL */
	{"VTOHBLANK", 16, 8, RW, 0x40},
	{"HBLANK", 8, 8, RW, 0x40},
	{"HTOVBLANK", 0, 8, RW, 0x40},
	/* CSIS_CMN_TEST_PATTERN_SIZE */
	{"TP_VSIZE", 16, 14, RW, 0x10},
	{"TP_HSIZE", 0, 14, RW, 0x10},
	/* CSIS_CMN_DMA_CFG_CSISX */
	{"AUTO_FLUSH_EN", 31, 1, RW, 0x0},
	{"MAX_16BL", 28, 1, RW, 0x1},
	{"BUSINFO", 16, 10, RW, 0x0},
	{"VOTF_EN_CH3", 15, 1, RW, 0x0},
	{"VOTF_EN_CH2", 14, 1, RW, 0x0},
	{"VOTF_EN_CH1", 13, 1, RW, 0x0},
	{"VOTF_EN_CH0", 12, 1, RW, 0x0},
	{"VOTF_STALL_EN", 11, 1, RW, 0x0},
	{"CSIS_WDMA_CLK_ALWAYS_ON", 10, 1, RW, 0x0},
	{"MAX_MO", 0, 10, RW, 0x100},
	/* CSIS_CMN_SBWC_SEL */
	{"SBWC_SEL_F7", 28, 4, RW, 0x0},
	{"SBWC_SEL_F6", 24, 4, RW, 0x0},
	{"SBWC_SEL_F5", 20, 4, RW, 0x0},
	{"SBWC_SEL_F4", 16, 4, RW, 0x0},
	{"SBWC_SEL_F3", 13, 3, RW, 0x0},
	{"SBWC_SEL_F2", 8, 5, RW, 0x0},
	{"SBWC_SEL_F1", 4, 4, RW, 0x0},
	{"SBWC_SEL_F0", 0, 4, RW, 0x0},
	/* CSIS_CMN_SBWC_TURN_CNT */
	{"CSIS_CMN_SBWC_TURN", 0, 4, RW, 0x0},
	{"CSIS_CMN_SBWC_TURN_CNT_CLEAR", 31, 1, RW, 0x0},
	/* CSIS_CMN_FRO_CSIS_MODE */
	{"FRO_CSIS_SEL", 8, 2, RW, 0x0},
	{"FRO_CSIS_MODE", 0, 1, RW, 0x0},
	/* CSIS_CMN_CUE_FLAG */
	{"FRO_CUE_FLAG_SET", 0, 1, WTC, 0x0},
	/* CSIS_CMN_CUE_FRAME_PTR */
	{"CUE_FRAME_PTR_CH3", 24, 5, RO, 0x0},
	{"CUE_FRAME_PTR_CH2", 16, 5, RO, 0x0},
	{"CUE_FRAME_PTR_CH1", 8, 5, RO, 0x0},
	{"CUE_FRAME_PTR_CH0", 0, 5, RO, 0x0},
	/* CSIS_CMN_SECURITYX */
	{"SEQIDX_SECURITY", 0, 1, RO, 0x0},
	/* CSIS_CMN_QURGENT_EN */
	{"EBUF_QURGENT_EN", 1, 1, RW, 0x0},
	{"DMA_QURGENT_EN", 0, 1, RW, 0x0},
	/* CSIS_CMN_VOTF_CFG */
	{"VOTF_USE_LEGACY_RING", 0, 1, RW, 0x0},
	/* CSIS_CMN_OVERFLOW_INT_ENABLE */
	{"INT_ENABLE", 0, 5, RW, 0x0},
	/* CSIS_CMN_OVERFLOW_INT_SRC */
	{"INT_SRC", 0, 5, RW, 0x0},
	/* CSIS_CMN_OVERFLOW_DBG_INFOX */
	{"DBG_INFOX", 0, 32, RO, 0x0},
	/* CSIS_CMN_FRO_CUR_FRAME_ID0 */
	{"FRO_CUR_FRAME_ID7", 28, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID6", 24, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID5", 20, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID4", 16, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID3", 12, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID2", 8, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID1", 4, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID0", 0, 4, RO, 0x0},
	/* CSIS_CMN_FRO_CUR_FRAME_ID1 */
	{"FRO_CUR_FRAME_ID15", 28, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID14", 24, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID13", 20, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID12", 16, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID11", 12, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID10", 8, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID9", 4, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID8", 0, 4, RO, 0x0},
	/* CSIS_CMN_FRO_CUR_FRAME_ID2 */
	{"FRO_CUR_FRAME_ID23", 28, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID22", 24, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID21", 20, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID20", 16, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID19", 12, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID18", 8, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID17", 4, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID16", 0, 4, RO, 0x0},
	/* CSIS_CMN_FRO_CUR_FRAME_ID3 */
	{"FRO_CUR_FRAME_ID31", 28, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID30", 24, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID29", 20, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID28", 16, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID27", 12, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID26", 8, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID25", 4, 4, RO, 0x0},
	{"FRO_CUR_FRAME_ID24", 0, 4, RO, 0x0},
	/* CSIS_CMN_FRO_PREV_FRAME_ID0 */
	{"FRO_PREV_FRAME_ID7", 28, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID6", 24, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID5", 20, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID4", 16, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID3", 12, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID2", 8, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID1", 4, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID0", 0, 4, RO, 0x0},
	/* CSIS_CMN_FRO_PREV_FRAME_ID1 */
	{"FRO_PREV_FRAME_ID15", 28, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID14", 24, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID13", 20, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID12", 16, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID11", 12, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID10", 8, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID9", 4, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID8", 0, 4, RO, 0x0},
	/* CSIS_CMN_FRO_PREV_FRAME_ID2 */
	{"FRO_PREV_FRAME_ID23", 28, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID22", 24, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID21", 20, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID20", 16, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID19", 12, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID18", 8, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID17", 4, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID16", 0, 4, RO, 0x0},
	/* CSIS_CMN_FRO_PREV_FRAME_ID3 */
	{"FRO_PREV_FRAME_ID31", 28, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID30", 24, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID29", 20, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID28", 16, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID27", 12, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID26", 8, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID25", 4, 4, RO, 0x0},
	{"FRO_PREV_FRAME_ID24", 0, 4, RO, 0x0},
	/* CSIS_CMN_DEBUG_EN */
	{"DMA_CAPTURE_ONCE", 1, 1, RW, 0x0},
	{"DMA_DEBUG_ENABLE", 0, 1, RW, 0x0},
	/* CSIS_CMN_DEBUG_INFO_CSISX_CHX_VCNT */
	{"DMAX_CHX_VCNT", 0, 32, RO, 0x0},
	/* CSIS_CMN_DEBUG_INFO_CSISX_CHX_HDCNT */
	{"DMAX_CHX_HDCNT", 0, 32, RO, 0x0},
	/* CSIS_CMN_DEBUG_INFO_AXI_DBG_CNT */
	{"AXI_DBG_CNT", 0, 32, RO, 0x10000},
	/* CSIS_CMN_DEBUG_INFO_AXI_BLK_CNT_MX */
	{"AXI_BLK_CNT_MX", 0, 32, RO, 0x0},
	/* CSIS_CMN_DEBUG_INFO_AXI_MO_CNT_MX */
	{"AXI_MO_CNT_MX", 0, 32, RO, 0x0},
};

/* CSIS_DMAX(5 masters)_CHX(4 channels) regs */
enum is_hw_csi_dmax_chx_reg_name {
	CSIS_DMAX_CHX_R_CTRL,
	CSIS_DMAX_CHX_R_FMT,
	CSIS_DMAX_CHX_R_SKIP,
	CSIS_DMAX_CHX_R_SKIP_SEQ,
	CSIS_DMAX_CHX_R_ADDR1,
	CSIS_DMAX_CHX_R_ADDR2,
	CSIS_DMAX_CHX_R_ADDR3,
	CSIS_DMAX_CHX_R_ADDR4,
	CSIS_DMAX_CHX_R_ADDR5,
	CSIS_DMAX_CHX_R_ADDR6,
	CSIS_DMAX_CHX_R_ADDR7,
	CSIS_DMAX_CHX_R_ADDR8,
	CSIS_DMAX_CHX_R_ADDR9,
	CSIS_DMAX_CHX_R_ADDR10,
	CSIS_DMAX_CHX_R_ADDR11,
	CSIS_DMAX_CHX_R_ADDR12,
	CSIS_DMAX_CHX_R_ADDR13,
	CSIS_DMAX_CHX_R_ADDR14,
	CSIS_DMAX_CHX_R_ADDR15,
	CSIS_DMAX_CHX_R_ADDR16,
	CSIS_DMAX_CHX_R_ADDR17,
	CSIS_DMAX_CHX_R_ADDR18,
	CSIS_DMAX_CHX_R_ADDR19,
	CSIS_DMAX_CHX_R_ADDR20,
	CSIS_DMAX_CHX_R_ADDR21,
	CSIS_DMAX_CHX_R_ADDR22,
	CSIS_DMAX_CHX_R_ADDR23,
	CSIS_DMAX_CHX_R_ADDR24,
	CSIS_DMAX_CHX_R_ADDR25,
	CSIS_DMAX_CHX_R_ADDR26,
	CSIS_DMAX_CHX_R_ADDR27,
	CSIS_DMAX_CHX_R_ADDR28,
	CSIS_DMAX_CHX_R_ADDR29,
	CSIS_DMAX_CHX_R_ADDR30,
	CSIS_DMAX_CHX_R_ADDR31,
	CSIS_DMAX_CHX_R_ADDR32,
	CSIS_DMAX_CHX_R_ADDR_SET_B,
	CSIS_DMAX_CHX_R_ACT_CTRL,
	CSIS_DMAX_CHX_R_ACT_FRAMECNT_SEQ,
	CSIS_DMAX_CHX_R_ACT_FMT,
	CSIS_DMAX_CHX_R_ACT_SKIP,
	CSIS_DMAX_CHX_R_ACT_SKIP_SEQ,
	CSIS_DMAX_CHX_R_RESOL,
	CSIS_DMAX_CHX_R_STRIDE,
	CSIS_DMAX_CHX_R_FCNTSEQ,
	CSIS_DMAX_CHX_R_FCNTSEQ_STAT,
	CSIS_DMAX_CHX_R_FRO_FRM,
	CSIS_DMAX_CHX_R_FRAME_SEQ_COUNTER,
	CSIS_DMAX_CHX_R_FRAME_SEQ_COUNTER_RESET,
	CSIS_DMAX_CHX_R_FRAME_SEQ_COUNTER_LAST_SHADOW_TRIG,
	CSIS_DMAX_CHX_REG_CNT
};

static const struct is_reg csi_dmax_chx_regs[CSIS_DMAX_CHX_REG_CNT] = {
	{0x0000, "CSIS_DMAX_CHX_CTRL"},
	{0x0004, "CSIS_DMAX_CHX_FMT"},
	{0x0008, "CSIS_DMAX_CHX_SKIP"},
	{0x000C, "CSIS_DMAX_CHX_SKIP_SEQ"},
	{0x0010, "CSIS_DMAX_CHX_ADDR1"},
	{0x0014, "CSIS_DMAX_CHX_ADDR2"},
	{0x0018, "CSIS_DMAX_CHX_ADDR3"},
	{0x001C, "CSIS_DMAX_CHX_ADDR4"},
	{0x0020, "CSIS_DMAX_CHX_ADDR5"},
	{0x0024, "CSIS_DMAX_CHX_ADDR6"},
	{0x0028, "CSIS_DMAX_CHX_ADDR7"},
	{0x002C, "CSIS_DMAX_CHX_ADDR8"},
	{0x0030, "CSIS_DMAX_CHX_ADDR9"},
	{0x0034, "CSIS_DMAX_CHX_ADDR10"},
	{0x0038, "CSIS_DMAX_CHX_ADDR11"},
	{0x003C, "CSIS_DMAX_CHX_ADDR12"},
	{0x0040, "CSIS_DMAX_CHX_ADDR13"},
	{0x0044, "CSIS_DMAX_CHX_ADDR14"},
	{0x0048, "CSIS_DMAX_CHX_ADDR15"},
	{0x004C, "CSIS_DMAX_CHX_ADDR16"},
	{0x0050, "CSIS_DMAX_CHX_ADDR17"},
	{0x0054, "CSIS_DMAX_CHX_ADDR18"},
	{0x0058, "CSIS_DMAX_CHX_ADDR19"},
	{0x005C, "CSIS_DMAX_CHX_ADDR20"},
	{0x0060, "CSIS_DMAX_CHX_ADDR21"},
	{0x0064, "CSIS_DMAX_CHX_ADDR22"},
	{0x0068, "CSIS_DMAX_CHX_ADDR23"},
	{0x006C, "CSIS_DMAX_CHX_ADDR24"},
	{0x0070, "CSIS_DMAX_CHX_ADDR25"},
	{0x0074, "CSIS_DMAX_CHX_ADDR26"},
	{0x0078, "CSIS_DMAX_CHX_ADDR27"},
	{0x007C, "CSIS_DMAX_CHX_ADDR28"},
	{0x0080, "CSIS_DMAX_CHX_ADDR29"},
	{0x0084, "CSIS_DMAX_CHX_ADDR30"},
	{0x0088, "CSIS_DMAX_CHX_ADDR31"},
	{0x008C, "CSIS_DMAX_CHX_ADDR32"},
	{0x00d0, "CSIS_DMAX_CHX_ADDR_SET_B"},
	{0x0090, "CSIS_DMAX_CHX_ACT_CTRL"},
	{0x0094, "CSIS_DMAX_CHX_ACT_FRAMECNT_SEQ"},
	{0x0098, "CSIS_DMAX_CHX_ACT_FMT"},
	{0x009C, "CSIS_DMAX_CHX_ACT_SKIP"},
	{0x00A0, "CSIS_DMAX_CHX_ACT_SKIP_SEQ"},
	{0x00A4, "CSIS_DMAX_CHX_RESOL"},
	{0x00A8, "CSIS_DMAX_CHX_STRIDE"},
	{0x00B0, "CSIS_DMAX_CHX_FCNTSEQ"},
	{0x00B4, "CSIS_DMAX_CHX_FCNTSEQ_STAT"},
	{0x00B8, "CSIS_DMAX_CHX_FRO_FRM"},
	{0x00C0, "CSIS_DMAX_CHX_FRAME_SEQ_COUNTER"},
	{0x00C4, "CSIS_DMAX_CHX_FRAME_SEQ_COUNTER_RESET"},
	{0x00C8, "CSIS_DMAX_CHX_FRAME_SEQ_COUNTER_LAST_SHADOW_TRIG"},
};

enum is_hw_csi_dmax_chx_reg_field {
	/* CSIS_DMAX_CHX_CTRL */
	CSIS_DMAX_CHX_F_ADDRESS_VIOLATION_AUTOFLUSH_ENABLE,
	CSIS_DMAX_CHX_F_OVERLAP_AUTOFLUSH_EN,
	CSIS_DMAX_CHX_F_UPDT_SKIPPTR,
	CSIS_DMAX_CHX_F_UPDT_FRAMEPTR,
	CSIS_DMAX_CHX_F_UPDT_PTR_EN,
	CSIS_DMAX_CHX_F_DMA_ENABLE,
	/* CSIS_DMAX_CHX_FMT */
	CSIS_DMAX_CHX_F_VARIABLE_LENGTH,
	CSIS_DMAX_CHX_F_DIM,
	CSIS_DMAX_CHX_F_BYTESWAP,
	CSIS_DMAX_CHX_F_DATAFORMAT,
	/* CSIS_DMAX_CHX_SKIP */
	CSIS_DMAX_CHX_F_SKIP_EN,
	CSIS_DMAX_CHX_F_SKIP_TURNPTR,
	/* CSIS_DMAX_CHX_SKIP_SEQ */
	CSIS_DMAX_CHX_F_SKIP_SEQ,
	/* CSIS_DMAX_CHX_ADDRX*/
	CSIS_DMAX_CHX_F_BASEADDR,
	/* CSIS_DMAX_CHX_ADDR_SET_B */
	CSIS_DMAX_CHX_F_BASEADDR_SET_B,
	/* CSIS_DMAX_CHX_ACT_CTRL */
	CSIS_DMAX_CHX_F_ACTIVE_ABORTED,
	CSIS_DMAX_CHX_F_ACTIVE_SKIPPTR,
	CSIS_DMAX_CHX_F_ACTIVE_FRAMEPTR,
	CSIS_DMAX_CHX_F_ACTIVE_ENABLE,
	/* CSIS_DMAX_CHX_ACT_FRAMECNT_SEQ */
	CSIS_DMAX_CHX_F_ACTIVE_FRAMECNT_SEQ,
	/* CSIS_DMAX_CHX_ACT_FMT */
	CSIS_DMAX_CHX_F_ACTIVE_DIM,
	CSIS_DMAX_CHX_F_ACTIVE_BYTESWAP,
	CSIS_DMAX_CHX_F_ACTIVE_DATAFORMAT,
	/* CSIS_DMAX_CHX_ACT_SKIP */
	CSIS_DMAX_CHX_F_ACTIVE_SKIP_EN,
	CSIS_DMAX_CHX_F_ACTIVE_SKIP_TURNPTR,
	/* CSIS_DMAX_CHX_ACT_SKIP_SEQ */
	CSIS_DMAX_CHX_F_ACTIVE_SKIP_SEQ,
	/* CSIS_DMAX_CHX_RESOL */
	CSIS_DMAX_CHX_F_VRESOL,
	CSIS_DMAX_CHX_F_HRESOL,
	/* CSIS_DMAX_CHX_STRIDE */
	CSIS_DMAX_CHX_F_STRIDE,
	/* CSIS_DMAX_CHX_FCNTSEQ */
	CSIS_DMAX_CHX_F_FRAMECNT_SEQ,
	/* CSIS_DMAX_CHX_FCNTSEQ_STAT */
	CSIS_DMAX_CHX_F_FRAMECNT_BEFORE,
	CSIS_DMAX_CHX_F_FRAMECNT_PRESENT,
	/* CSIS_DMAX_CHX_FRO_FRM */
	CSIS_DMAX_CHX_F_CUR_FRO_FRM,
	/* CSIS_DMAX_CHX_FRAME_SEQ_COUNTER */
	CSIS_DMAX_CHX_F_FRAME_SEQ_COUNTER,
	/* CSIS_DMAX_CHX_FRAME_SEQ_COUNTER_RESET */
	CSIS_DMAX_CHX_F_FRAME_SEQ_COUNTER_RESET,
	/* CSIS_DMAX_CHX_FRAME_SEQ_COUNTER_LAST_SHADOW_TRIG */
	CSIS_DMAX_CHX_F_FRAME_SEQ_COUNTER_LAST_SHADOW_TRIG,
	CSIS_DMAX_CHX_REG_FIELD_CNT
};

static const struct is_field csi_dmax_chx_fields[CSIS_DMAX_CHX_REG_FIELD_CNT] = {
	/* CSIS_DMAX_CHX_CTRL */
	{"address_violation_autoflush_enable", 13, 1, RW, 0x0},
	{"overlap_autoflush_enable", 12, 1, RW, 0x0},
	{"UPDT_SKIPPTR", 7, 5, RW, 0x0},
	{"UPDT_FRAMEPTR", 2, 5, RW, 0x0},
	{"UPDT_PTR_EN", 1, 1, RW, 0x0},
	{"DMA_ENABLE", 0, 1, RW, 0x0},
	/* CSIS_DMAX_CHX_FMT */
	{"VARIABLE_LENGTH", 7, 1, RW, 0x0},
	{"DIM", 6, 1, RW, 0x0},
	{"BYTESWAP", 5, 1, RW, 0x0},
	{"DATAFORMAT", 0, 5, RW, 0x0},
	/* CSIS_DMAX_CHX_SKIP */
	{"SKIP_EN", 31, 1, RW, 0x0},
	{"SKIP_TURNPTR", 16, 5, RW, 0x0},
	/* CSIS_DMAX_CHX_SKIP_SEQ */
	{"SKIP_SEQ", 0, 32, RW, 0x0},
	/* CSIS_DMAX_CHX_ADDRX*/
	{"BASEADDR", 0, 32, RW, 0x0},
	/* CSIS_DMAX_CHX_ADDR_SET_B */
	{"BaseAddr_set_b", 0, 32, RW, 0x0},
	/* CSIS_DMAX_CHX_ACT_CTRL */
	{"Active_Aborted", 16, 1, RWI, 0x0},
	{"Active_SkipPtr", 7, 5, RWI, 0x0},
	{"Active_FramePtr", 2, 5, RWI, 0x1f},
	{"Active_Enable", 0, 1, RWI, 0x0},
	/* CSIS_DMAX_CHX_ACT_FRAMECNT_SEQ */
	{"Active_FrameCnt_Seq", 0, 32, RWI, 0xffffffff},
	/* CSIS_DMAX_CHX_ACT_FMT */
	{"Active_Dim", 6, 1, RWI, 0x0},
	{"Active_ByteSwap", 5, 1, RWI, 0x0},
	{"Active_DataFormat", 0, 5, RWI, 0x0},
	/* CSIS_DMAX_CHX_ACT_SKIP */
	{"Active_Skip_En", 31, 1, RWI, 0x0},
	{"Active_Skip_TurnPtr", 16, 5, RWI, 0x0},
	/* CSIS_DMAX_CHX_ACT_SKIP_SEQ */
	{"Active_Skip_Seq", 0, 32, RWI, 0x0},
	/* CSIS_DMAX_CHX_RESOL */
	{"VResol", 16, 16, RW, 0x0},
	{"HRESOL", 0, 16, RW, 0x0},
	/* CSIS_DMAX_CHX_STRIDE */
	{"STRIDE", 0, 32, RW, 0x0},
	/* CSIS_DMAX_CHX_FCNTSEQ */
	{"FRAMECNT_SEQ", 0, 32, RW, 0xffffffff},
	/* CSIS_DMAX_CHX_FCNTSEQ_STAT */
	{"FrameCnt_before", 8, 6, RWI, 0x0},
	{"FrameCnt_present", 0, 6, RWI, 0x0},
	/* CSIS_DMAX_CHX_FRO_FRM */
	{"CUR_FRO_FRM", 0, 4, RW, 0x0},
	/* CSIS_DMAX_CHX_FRAME_SEQ_COUNTER */
	{"frame_seq_counter", 0, 32, RWI, 0x0},
	/* CSIS_DMAX_CHX_FRAME_SEQ_COUNTER_RESET */
	{"FRAME_SEQ_COUNTER_RESET", 0, 1, RW, 0x0},
	/* CSIS_DMAX_CHX_FRAME_SEQ_COUNTER_LAST_SHADOW_TRIG */
	{"frame_seq_counter_last_shadow_trig", 0, 32, RWI, 0x0},
};

/* CSIS_DMAX(5 masters) regs */
enum is_hw_csi_dmax_reg_name {
	CSIS_DMAX_R_DATA_CTRL,
	CSIS_DMAX_R_INT_ENABLE,
	CSIS_DMAX_R_INT_SRC,
	CSIS_DMAX_R_CMN_CTRL,
	CSIS_DMAX_R_FRO_INT_FRAME_NUM,
	CSIS_DMAX_R_FRO_CH0_DROPPED_FRAME,
	CSIS_DMAX_R_FRO_CH1_DROPPED_FRAME,
	CSIS_DMAX_R_FRO_CH2_DROPPED_FRAME,
	CSIS_DMAX_R_FRO_CH3_DROPPED_FRAME,
	CSIS_DMAX_R_SBWC_CTRL,
	CSIS_DMAX_R_SBWC_HEADER_ADDR1,
	CSIS_DMAX_R_SBWC_HEADER_ADDR2,
	CSIS_DMAX_R_SBWC_HEADER_ADDR3,
	CSIS_DMAX_R_SBWC_HEADER_ADDR4,
	CSIS_DMAX_R_SBWC_HEADER_ADDR5,
	CSIS_DMAX_R_SBWC_HEADER_ADDR6,
	CSIS_DMAX_R_SBWC_HEADER_ADDR7,
	CSIS_DMAX_R_SBWC_HEADER_ADDR8,
	CSIS_DMAX_R_SBWC_HEADER_ADDR9,
	CSIS_DMAX_R_SBWC_HEADER_ADDR10,
	CSIS_DMAX_R_SBWC_HEADER_ADDR11,
	CSIS_DMAX_R_SBWC_HEADER_ADDR12,
	CSIS_DMAX_R_SBWC_HEADER_ADDR13,
	CSIS_DMAX_R_SBWC_HEADER_ADDR14,
	CSIS_DMAX_R_SBWC_HEADER_ADDR15,
	CSIS_DMAX_R_SBWC_HEADER_ADDR16,
	CSIS_DMAX_R_SBWC_HEADER_ADDR17,
	CSIS_DMAX_R_SBWC_HEADER_ADDR18,
	CSIS_DMAX_R_SBWC_HEADER_ADDR19,
	CSIS_DMAX_R_SBWC_HEADER_ADDR20,
	CSIS_DMAX_R_SBWC_HEADER_ADDR21,
	CSIS_DMAX_R_SBWC_HEADER_ADDR22,
	CSIS_DMAX_R_SBWC_HEADER_ADDR23,
	CSIS_DMAX_R_SBWC_HEADER_ADDR24,
	CSIS_DMAX_R_SBWC_HEADER_ADDR25,
	CSIS_DMAX_R_SBWC_HEADER_ADDR26,
	CSIS_DMAX_R_SBWC_HEADER_ADDR27,
	CSIS_DMAX_R_SBWC_HEADER_ADDR28,
	CSIS_DMAX_R_SBWC_HEADER_ADDR29,
	CSIS_DMAX_R_SBWC_HEADER_ADDR30,
	CSIS_DMAX_R_SBWC_HEADER_ADDR31,
	CSIS_DMAX_R_SBWC_HEADER_ADDR32,
	CSIS_DMAX_R_SBWC_HEADER_STRIDE,
	CSIS_DMAX_R_ACT_SBWC_CTRL,
	CSIS_DMAX_R_SBWC_HEADER_SET_B,
	CSIS_DMAX_R_LOSSY_BYTE32NUM,
	CSIS_DMAX_REG_CNT
};

static const struct is_reg csi_dmax_regs[CSIS_DMAX_REG_CNT] = {
	{0x0000, "CSIS_DMAX_DATA_CTRL"},
	{0x0004, "CSIS_DMAX_INT_ENABLE"},
	{0x0008, "CSIS_DMAX_INT_SRC"},
	{0x0014, "CSIS_DMAX_CMN_CTRL"},
	{0x0020, "CSIS_DMAX_FRO_INT_FRAME_NUM"},
	{0x0024, "CSIS_DMAX_FRO_CH0_DROPPED_FRAME"},
	{0x0028, "CSIS_DMAX_FRO_CH1_DROPPED_FRAME"},
	{0x002C, "CSIS_DMAX_FRO_CH2_DROPPED_FRAME"},
	{0x0030, "CSIS_DMAX_FRO_CH3_DROPPED_FRAME"},
	{0x0040, "CSIS_DMAX_SBWC_CTRL"},
	{0x0044, "CSIS_DMAX_SBWC_HEADER_ADDR1"},
	{0x0048, "CSIS_DMAX_SBWC_HEADER_ADDR2"},
	{0x004C, "CSIS_DMAX_SBWC_HEADER_ADDR3"},
	{0x0050, "CSIS_DMAX_SBWC_HEADER_ADDR4"},
	{0x0054, "CSIS_DMAX_SBWC_HEADER_ADDR5"},
	{0x0058, "CSIS_DMAX_SBWC_HEADER_ADDR6"},
	{0x005C, "CSIS_DMAX_SBWC_HEADER_ADDR7"},
	{0x0060, "CSIS_DMAX_SBWC_HEADER_ADDR8"},
	{0x0064, "CSIS_DMAX_SBWC_HEADER_ADDR9"},
	{0x0068, "CSIS_DMAX_SBWC_HEADER_ADDR10"},
	{0x006C, "CSIS_DMAX_SBWC_HEADER_ADDR11"},
	{0x0070, "CSIS_DMAX_SBWC_HEADER_ADDR12"},
	{0x0074, "CSIS_DMAX_SBWC_HEADER_ADDR13"},
	{0x0078, "CSIS_DMAX_SBWC_HEADER_ADDR14"},
	{0x007C, "CSIS_DMAX_SBWC_HEADER_ADDR15"},
	{0x0080, "CSIS_DMAX_SBWC_HEADER_ADDR16"},
	{0x0084, "CSIS_DMAX_SBWC_HEADER_ADDR17"},
	{0x0088, "CSIS_DMAX_SBWC_HEADER_ADDR18"},
	{0x008C, "CSIS_DMAX_SBWC_HEADER_ADDR19"},
	{0x0090, "CSIS_DMAX_SBWC_HEADER_ADDR20"},
	{0x0094, "CSIS_DMAX_SBWC_HEADER_ADDR21"},
	{0x0098, "CSIS_DMAX_SBWC_HEADER_ADDR22"},
	{0x009C, "CSIS_DMAX_SBWC_HEADER_ADDR23"},
	{0x00A0, "CSIS_DMAX_SBWC_HEADER_ADDR24"},
	{0x00A4, "CSIS_DMAX_SBWC_HEADER_ADDR25"},
	{0x00A8, "CSIS_DMAX_SBWC_HEADER_ADDR26"},
	{0x00AC, "CSIS_DMAX_SBWC_HEADER_ADDR27"},
	{0x00B0, "CSIS_DMAX_SBWC_HEADER_ADDR28"},
	{0x00B4, "CSIS_DMAX_SBWC_HEADER_ADDR29"},
	{0x00B8, "CSIS_DMAX_SBWC_HEADER_ADDR30"},
	{0x00BC, "CSIS_DMAX_SBWC_HEADER_ADDR31"},
	{0x00C0, "CSIS_DMAX_SBWC_HEADER_ADDR32"},
	{0x00C4, "CSIS_DMAX_SBWC_HEADER_STRIDE"},
	{0x00C8, "CSIS_DMAX_ACT_SBWC_CTRL"},
	{0x00D0, "CSIS_DMAX_SBWC_HEADER_SET_B"},
	{0x00D4, "CSIS_DMAX_LOSSY_BYTE32NUM"},
};

enum is_hw_csi_dmax_reg_field {
	/* CSIS_DMAX_DATA_CTRL */
	CSIS_DMAX_F_DMA_INPUT_PATH_CH1,
	CSIS_DMAX_F_DMA_INPUT_PATH_CH0,
	/* CSIS_DMAX_INT_ENABLE */
	CSIS_DMAX_F_INT_ENABLE,
	/* CSIS_DMAX_INT_SRC */
	CSIS_DMAX_F_INT_SRC,
	/* CSIS_DMAX_CMN_CTRL */
	CSIS_DMAX_F_DMA_ABORT_REQ,
	/* CSIS_DMAX_FRO_INT_FRAME_NUM */
	CSIS_DMAX_F_FID_FRAME_NUM_CH3,
	CSIS_DMAX_F_FID_FRAME_NUM_CH2,
	CSIS_DMAX_F_FID_FRAME_NUM_CH1,
	CSIS_DMAX_F_FID_FRAME_NUM_CH0,
	CSIS_DMAX_F_FRO_FRAME_NUM_CH3,
	CSIS_DMAX_F_FRO_FRAME_NUM_CH2,
	CSIS_DMAX_F_FRO_FRAME_NUM_CH1,
	CSIS_DMAX_F_FRO_FRAME_NUM_CH0,
	/* CSIS_DMAX_FRO_CHX_DROPPED_FRAME */
	CSIS_DMAX_F_DROPPED_FRAME_PTR,
	/* CSIS_DMAX_SBWC_CTRL */
	CSIS_DMAX_F_SBWC_ENABLE,
	CSIS_DMAX_F_SBWC_64B_ZERO_PAD_EN,
	CSIS_DMAX_F_SBWC_TETRACELL_EN,
	/* CSIS_DMAX_SBWC_HEADER_ADDRX */
	CSIS_DMAX_F_SBWC_HEADER_BASE_ADDR,
	/* CSIS_DMAX_SBWC_HEADER_STRIDE */
	CSIS_DMAX_F_SBWC_HEADER_STRIDE,
	/* CSIS_DMAX_ACT_SBWC_CTRL */
	CSIS_DMAX_F_ACTIVE_SKIP_SEQ,
	/* CSIS_DMAX_SBWC_HEADER_SET_B */
	CSIS_DMAX_F_SBWC_HEADER_BASE_ADDR_SET_B,
	/* CSIS_DMAX_LOSSY_BYTE32NUM */
	CSIS_DMAX_F_LOSSY_BYTE32NUM,
	CSIS_DMAX_REG_FIELD_CNT
};

static struct is_field csi_dmax_fields[CSIS_DMAX_REG_FIELD_CNT] = {
	/* CSIS_DMAX_DATA_CTRL */
	{"DMA_INPUT_PATH_CH1", 1, 1, RW, 0x0},
	{"DMA_INPUT_PATH_CH0", 0, 1, RW, 0x0},
	/* CSIS_DMAX_INT_ENABLE */
	{"INT_ENABLE", 0, 32, RW, 0x0},
	/* CSIS_DMAX_INT_SRC */
	{"INT_SRC", 0, 32, RW, 0x0},
	/* CSIS_DMAX_CMN_CTRL */
	{"DMA_ABORT_REQ", 0, 1, RW, 0x0},
	/* CSIS_DMAX_FRO_INT_FRAME_NUM */
	{"FID_Frame_Num_ch3", 28, 4, RW, 0x0},
	{"FID_Frame_Num_ch2", 24, 4, RW, 0x0},
	{"FID_Frame_Num_ch1", 20, 4, RW, 0x0},
	{"FID_Frame_Num_ch0", 16, 4, RW, 0x0},
	{"FRO_FRAME_NUM_CH3", 12, 4, RW, 0x0},
	{"FRO_FRAME_NUM_CH2", 8, 4, RW, 0x0},
	{"FRO_FRAME_NUM_CH1", 4, 4, RW, 0x0},
	{"FRO_FRAME_NUM_CH0", 0, 4, RW, 0x0},
	/* CSIS_DMAX_FRO_CHX_DROPPED_FRAME */
	{"Dropped_Frame_Ptr", 0, 16, RWI, 0x0},
	/* CSIS_DMAX_SBWC_CTRL */
	{"SBWC_ENABLE", 0, 3, RW, 0x0},
	{"sbwc_64b_zero_pad_en", 3, 1, RW, 0x0},
	{"sbwc_tetracell_en", 4, 1, RW, 0x0},
	/* CSIS_DMAX_SBWC_HEADER_ADDRX */
	{"SBWC_HEADER_BASE_ADDR", 0, 32, RW, 0x0},
	/* CSIS_DMAX_SBWC_HEADER_STRIDE */
	{"SBWC_HEADER_STRIDE", 0, 32, RW, 0x0},
	/* CSIS_DMAX_ACT_SBWC_CTRL */
	{"ACTIVE_SKIP_SEQ", 0, 3, RO, 0x0},
	/* CSIS_DMAX_SBWC_HEADER_SET_B */
	{"sbwc_header_base_addr_set_b", 0, 32, RW, 0x0},
	/* CSIS_DMAX_LOSSY_BYTE32NUM */
	{"LOSSY_BYTE32NUM", 0, 4, RW, 0x0},
};

/* CSIS_FRO regs */
enum is_hw_csi_fro_reg_name {
	CSIS_FRO_R_FRO_NORMAL_OUTPUT_CTRL,
	CSIS_FRO_R_FRO_VOTF_VVALID_N_NORMAL_FLAG_CTRL,
	CSIS_FRO_REG_CNT
};

static const struct is_reg csi_fro_regs[CSIS_FRO_REG_CNT] = {
	{0x0000, "fro_normal_output_ctrl"},
	{0x0004, "fro_votf_vvalid_n_normal_flag_ctrl"},
};

enum is_hw_csi_fro_field {
	CSIS_FRO_F_NOMAL_FLAG_CTRL,
	CSIS_FRO_F_CSTAT_PATH_VOTF_VVALID_EN,
	CSIS_FRO_F_CSTAT_PATH_NORMAL_FLAG_EN,
	CSIS_FRO_F_PDP_PATH_VOTF_VVALID_EN,
	CSIS_FRO_F_PDP_PATH_NORMAL_FLAG_EN,
	CSIS_FRO_REF_FIELD_CNT
};

static struct is_field csi_fro_fields[CSIS_FRO_REF_FIELD_CNT] = {
	/* FRO_NORMAL_OUTPUT_CTRL */
	{"normal_flag_ctrl", 0, 5, RW, 0x0},
	/* FRO_VOTF_VVALID_N_NORMAL_FLAG_CTRL */
	{"cstat_path_votf_vvalid_en", 12, 4, RW, 0x0},
	{"cstat_path_normal_flag_en", 8, 4, RW, 0x0},
	{"pdp_path_votf_vvalid_en", 4, 4, RW, 0x0},
	{"pdp_path_normal_flag_en", 0, 4, RW, 0x0},
};

/* CSIS_MCBX (2 cores) regs */
enum is_hw_csi_mcb_reg_name {
	CSIS_MCB_R_MCBX_BYPASS,
	CSIS_MCB_R_MCBX_CRWIP_START,
	CSIS_MCB_R_MCBX_CRWIP_SIZE,
	CSIS_MCB_R_MCBX_OUTPUT_WIDTH,
	CSIS_MCB_R_MCBX_CRC,
	CSIS_MCB_REG_CNT
};

static const struct is_reg csi_mcb_regs[CSIS_MCB_REG_CNT] = {
	{0X0000, "MCBX_BYPASS"},
	{0X0004, "MCBX_CRWIP_START"},
	{0X0008, "MCBX_CRWIP_SIZE"},
	{0X000C, "MCBX_OUTPUT_WIDTH"},
	{0X00FC, "MCBX_CRC"},
};

enum is_hw_csi_mcb_reg_field {
	/* MCBX_BYPASS */
	CSIS_MCB_F_MCB_INPUT_WIDTH,
	CSIS_MCB_F_MCB_OBITMODE,
	CSIS_MCB_F_MCB_IBITMODE,
	CSIS_MCB_F_MCB_CROP_EN,
	CSIS_MCB_F_MCB_BINNINGMODE,
	CSIS_MCB_F_MCB_BYPASS,
	/* MCBX_CRWIP_START */
	CSIS_MCB_F_MCB_CROP_START_Y,
	CSIS_MCB_F_MCB_CROP_START_X,
	/* MCBX_CRWIP_SIZE */
	CSIS_MCB_F_MCB_CROP_SIZE_Y,
	CSIS_MCB_F_MCB_CROP_SIZE_X,
	/* MCBX_OUTPUT_WIDTH */
	CSIS_MCB_F_MCB_OUTPUT_WIDTH,
	/* MCBX_CRC */
	CSIS_MCB_F_MCB_CRC_RESULT,
	CSIS_MCB_F_MCB_CRC_SEED,
	CSIS_MCB_REG_FIELD_CNT
};

static struct is_field csi_mcb_fields[CSIS_MCB_REG_FIELD_CNT] = {
	/* MCBX_BYPASS */
	{"INPUT_WIDTH", 16, 15, RW, 0x0},
	{"OBITMODE", 14, 2, RW, 0x0},
	{"IBITMODE", 12, 2, RW, 0x0},
	{"CROP_EN", 8, 1, RW, 0x0},
	{"BINNINGMODE", 4, 2, RW, 0x0},
	{"BYPASS", 0, 1, RW, 0x1},
	/* MCBX_CRWIP_START */
	{"CROP_START_Y", 16, 15, RW, 0x0},
	{"CROP_START_X", 0, 15, RW, 0x0},
	/* MCBX_CRWIP_SIZE */
	{"CROP_SIZE_Y", 16, 15, RW, 0x0},
	{"CROP_SIZE_X", 0, 15, RW, 0x0},
	/* MCBX_OUTPUT_WIDTH */
	{"OUTPUT_WIDTH", 0, 15, RW, 0x0},
	/* MCBX_CRC */
	{"CRC_RESULT", 8, 8, RWI, 0x0},
	{"CRC_SEED", 0, 8, RW, 0x0},
};

/* CSIS_MCB_CMN regs */
enum is_hw_csi_mcb_cmn_reg_name {
	CSIS_MCB_CMN_R_QCH,
	CSIS_MCB_CMN_R_INPUT_MUX_0,
	CSIS_MCB_CMN_R_INPUT_MUX_1,
	CSIS_MCB_CMN_R_OUTPUT_MUX_0,
	CSIS_MCB_CMN_R_OUTPUT_MUX_1,
	CSIS_MCB_CMN_R_OUTPUT_MUX_2,
	CSIS_MCB_CMN_R_OUTPUT_MUX_3,
	CSIS_MCB_CMN_REG_CNT
};

static const struct is_reg csi_mcb_cmn_regs[CSIS_MCB_CMN_REG_CNT] = {
	{0X0000, "MCB_QCH"},
	{0X0004, "MCB_INPUT_MUX_0"},
	{0X0008, "MCB_INPUT_MUX_1"},
	{0X000C, "MCB_OUTPUT_MUX_0"},
	{0X0010, "MCB_OUTPUT_MUX_1"},
	{0X0014, "MCB_OUTPUT_MUX_2"},
	{0X0018, "MCB_OUTPUT_MUX_3"},
};

enum is_hw_csi_mcb_cmn_reg_field {
	/* MCB_QCH*/
	CSIS_MCB_CMN_F_MCB_DO_NOT_USE_CSTAT_FIFO,
	CSIS_MCB_CMN_F_MCB_SYNC_RESET_ALWAYS_ON,
	CSIS_MCB_CMN_F_MCB_FORCE_BUS_ACT_ON,
	CSIS_MCB_CMN_F_MCB_QACTIVE_ON,
	/* MCB_INPUT_MUX_X */
	CSIS_MCB_CMN_F_MCB_INPUT_MUX_SEL,
	/* MCB_OUTPUT_MUX_X */
	CSIS_MCB_CMN_F_MCB_OUTPUT_MUX_SEL,
	CSIS_MCB_CMN_REG_FIELD_CNT
};

static struct is_field csi_mcb_cmn_fields[CSIS_MCB_CMN_REG_FIELD_CNT] = {
	/* MCB_QCH*/
	{"DO_NOT_USE_CSTAT_FIFO", 16, 1, RW, 0x0},
	{"SYNC_RESET_ALWAYS_ON", 9, 1, RW, 0x0},
	{"FORCE_BUS_ACT_ON", 1, 1, RW, 0x0},
	{"QACTIVE_ON", 0, 1, RW, 0x1},
	/* MCB_INPUT_MUX_X */
	{"INPUT_MUX_SEL", 0, 2, RW, 0x0},
	/* MCB_OUTPUT_MUX_X */
	{"OUTPUT_MUX_SEL", 0, 2, RW, 0x0},
};

/* CSIS_EBUF regs */
enum is_hw_csi_ebuf_reg_name {
	CSIS_EBUF_R_EBUF_CTRL,
	CSIS_EBUF_R_EBUF_NUM_OF_CAMERAS,
	CSIS_EBUF_R_EBUF0_SW_RESET,
	CSIS_EBUF_R_EBUF0_CTRL_EN,
	CSIS_EBUF_R_EBUF0_OUT_SYNC_CTRL,
	CSIS_EBUF_R_EBUF0_GEN_FAKE_SIGNAL,
	CSIS_EBUF_R_EBUF0_CHID0_SIZE,
	CSIS_EBUF_R_EBUF0_CHID1_SIZE,
	CSIS_EBUF_R_EBUF1_SW_RESET,
	CSIS_EBUF_R_EBUF1_CTRL_EN,
	CSIS_EBUF_R_EBUF1_OUT_SYNC_CTRL,
	CSIS_EBUF_R_EBUF1_GEN_FAKE_SIGNAL,
	CSIS_EBUF_R_EBUF1_CHID0_SIZE,
	CSIS_EBUF_R_EBUF1_CHID1_SIZE,
	CSIS_EBUF_R_EBUF2_SW_RESET,
	CSIS_EBUF_R_EBUF2_CTRL_EN,
	CSIS_EBUF_R_EBUF2_OUT_SYNC_CTRL,
	CSIS_EBUF_R_EBUF2_GEN_FAKE_SIGNAL,
	CSIS_EBUF_R_EBUF2_CHID0_SIZE,
	CSIS_EBUF_R_EBUF2_CHID1_SIZE,
	CSIS_EBUF_R_EBUF3_SW_RESET,
	CSIS_EBUF_R_EBUF3_CTRL_EN,
	CSIS_EBUF_R_EBUF3_OUT_SYNC_CTRL,
	CSIS_EBUF_R_EBUF3_GEN_FAKE_SIGNAL,
	CSIS_EBUF_R_EBUF3_CHID0_SIZE,
	CSIS_EBUF_R_EBUF3_CHID1_SIZE,
	CSIS_EBUF_R_EBUF_INTR_STATUS,
	CSIS_EBUF_R_EBUF_INTR_ENABLE,
	CSIS_EBUF_R_EBUF_INTR_CLEAR,
	CSIS_EBUF_REG_CNT
};

static const struct is_reg csi_ebuf_regs[CSIS_EBUF_REG_CNT] = {
	{0X0000, "EBUF_CTRL"},
	{0X0004, "EBUF_NUM_OF_CAMERAS"},
	{0X0010, "EBUF0_SW_RESET"},
	{0X0014, "EBUF0_CTRL_EN"},
	{0X0018, "EBUF0_OUT_SYNC_CTRL"},
	{0X0020, "EBUF0_GEN_FAKE_SIGNAL"},
	{0X0024, "EBUF0_CHID0_SIZE"},
	{0X0028, "EBUF0_CHID1_SIZE"},
	{0X0030, "EBUF1_SW_RESET"},
	{0X0034, "EBUF1_CTRL_EN"},
	{0X0038, "EBUF1_OUT_SYNC_CTRL"},
	{0X0040, "EBUF1_GEN_FAKE_SIGNAL"},
	{0X0044, "EBUF1_CHID0_SIZE"},
	{0X0048, "EBUF1_CHID1_SIZE"},
	{0X0050, "EBUF2_SW_RESET"},
	{0X0054, "EBUF2_CTRL_EN"},
	{0X0058, "EBUF2_OUT_SYNC_CTRL"},
	{0X0060, "EBUF2_GEN_FAKE_SIGNAL"},
	{0X0064, "EBUF2_CHID0_SIZE"},
	{0X0068, "EBUF2_CHID1_SIZE"},
	{0X0070, "EBUF3_SW_RESET"},
	{0X0074, "EBUF3_CTRL_EN"},
	{0X0078, "EBUF3_OUT_SYNC_CTRL"},
	{0X0080, "EBUF3_GEN_FAKE_SIGNAL"},
	{0X0084, "EBUF3_CHID0_SIZE"},
	{0X0088, "EBUF3_CHID1_SIZE"},
	{0X00D0, "EBUF_INTR_STATUS"},
	{0X00D4, "EBUF_INTR_ENABLE"},
	{0X00D8, "EBUF_INTR_CLEAR"},
};

enum is_hw_csi_ebuf_reg_field {
	/* EBUF_CTRL */
	CSIS_EBUF_F_EBUF_BYPASS,
	/* EBUF_NUM_OF_CAMERAS */
	CSIS_EBUF_F_NUM_OF_CAMERAS,
	/* EBUFX_SW_RESET */
	CSIS_EBUF_F_EBUFX_SW_RESET,
	/* EBUFX_CTRL_EN */
	CSIS_EBUF_F_EBUFX_ABORT_LIC_BUSY_EN,
	CSIS_EBUF_F_EBUFX_ABORT_AUTO_GEN_FAKE,
	CSIS_EBUF_F_EBUFX_ABORT_CTRL_EN,
	/* EBUFX_OUT_SYNC_CTRL */
	CSIS_EBUF_F_EBUFX_OUT_MIN_HBLANK,
	/* EBUFX_GEN_FAKE_SIGNAL */
	CSIS_EBUF_F_EBUFX_GEN_FAKE_SIGNAL,
	/* EBUFX_CHIDX_SIZE */
	CSIS_EBUF_F_EBUFX_CHIDX_SIZE_V,
	CSIS_EBUF_F_EBUFX_CHIDX_SIZE_H,
	/* EBUF_INTR_STATUS */
	CSIS_EBUF_F_EBUF_INTR_STATUS,
	/* EBUF_INTR_ENABLE */
	CSIS_EBUF_F_EBUF_INTR_ENABLE,
	/* EBUF_INTR_CLEAR */
	CSIS_EBUF_F_EBUF_INTR_CLEAR,
	CSIS_EBUF_REG_FIELD_CNT
};

static struct is_field csi_ebuf_fields[CSIS_EBUF_REG_FIELD_CNT] = {
	/* EBUF_CTRL */
	{"BYPASS", 0, 1, RW, 0x1},
	/* EBUF_NUM_OF_CAMERAS */
	{"NUM_OF_CAMERAS", 0, 2, RW, 0x0},
	/* EBUFX_SW_RESET */
	{"EBUFX_SW_RESET", 0, 1, RIW, 0x0},
	/* EBUFX_CTRL_EN */
	{"EBUFX_ABORT_LIC_BUSY_EN", 3, 1, RW, 0x0},
	{"EBUFX_ABORT_AUTO_GEN_FAKE", 2, 1, RW, 0x0},
	{"EBUFX_ABORT_CTRL_EN", 1, 1, RW, 0x0},
	/* EBUFX_OUT_SYNC_CTRL */
	{"EBUFX_OUT_MIN_HBLANK", 0, 16, RW, 0x0},
	/* EBUFX_GEN_FAKE_SIGNAL */
	{"EBUFX_GEN_FAKE_SIGNAL", 0, 1, RIW, 0x0},
	/* EBUFX_CHIDX_SIZE */
	{"EBUFX_CHIDX_SIZE_V", 16, 16, RW, 0x0},
	{"EBUFX_CHIDX_SIZE_H", 0, 16, RW, 0x0},
	/* EBUF_INTR_STATUS */
	{"INTR_STATUS", 0, 8, RO, 0x0},
	/* EBUF_INTR_ENABLE */
	{"INTR_ENABLE", 0, 8, RW, 0x0},
	/* EBUF_INTR_CLEAR */
	{"INTR_CLEAR", 0, 8, RIW, 0x0},
};

/* CSIS_BNS regs */
enum is_hw_csi_bns_reg_name {
	CSIS_BNS_R_BYR_BNS_BYPASS,
	CSIS_BNS_R_BYR_BNS_CONFIG,
	CSIS_BNS_R_BYR_BNS_INPUTSIZE,
	CSIS_BNS_R_BYR_BNS_OUTPUTSIZE,
	CSIS_BNS_R_BYR_BNS_WEIGHT_X_0,
	CSIS_BNS_R_BYR_BNS_WEIGHT_X_4,
	CSIS_BNS_R_BYR_BNS_WEIGHT_Y_0,
	CSIS_BNS_R_BYR_BNS_WEIGHT_Y_4,
	CSIS_BNS_R_BYR_BNS_STREAM_CRC,
	CSIS_BNS_REG_CNT
};

static const struct is_reg csi_bns_regs[CSIS_BNS_REG_CNT] = {
	{0X0000, "BNS_BYPASS"},
	{0X0004, "BNS_CONFIG"},
	{0X0010, "BNS_INPUTSIZE"},
	{0X0014, "BNS_OUTPUTSIZE"},
	{0X0020, "BNS_WEIGHT_X_0"},
	{0X0024, "BNS_WEIGHT_X_4"},
	{0X0030, "BNS_WEIGHT_Y_0"},
	{0X0034, "BNS_WEIGHT_Y_4"},
	{0X00FC, "BNS_STREAM_CRC"},
};

enum is_hw_csi_bns_reg_field {
	/* BNS_BYPASS */
	CSIS_BNS_F_BNS_BYPASS,
	/* BNS_CONFIG */
	CSIS_BNS_F_BNS_BITTAGE,
	CSIS_BNS_F_BNS_FACTOR_Y,
	CSIS_BNS_F_BNS_FACTOR_X,
	/* BNS_INPUTSIZE */
	CSIS_BNS_F_BNS_INPUT_TOTAL_HEIGHT,
	CSIS_BNS_F_BNS_INPUT_TOTAL_WIDTH,
	/* BNS_OUTPUTSIZE */
	CSIS_BNS_F_BNS_OUTPUT_TOTAL_HEIGHT,
	CSIS_BNS_F_BNS_OUTPUT_TOTAL_WIDTH,
	/* BNS_WEIGHT_0_X */
	CSIS_BNS_F_BNS_WEIGHT_0_3,
	CSIS_BNS_F_BNS_WEIGHT_0_2,
	CSIS_BNS_F_BNS_WEIGHT_0_1,
	CSIS_BNS_F_BNS_WEIGHT_0_0,
	/* BNS_WEIGHT_0_4 */
	CSIS_BNS_F_BNS_WEIGHT_0_4,
	/* BNS_STREAM_CRC */
	CSIS_BNS_F_BNS_CRC_RESULT,
	CSIS_BNS_F_BNS_CRC_SEED,
	CSIS_BNS_REG_FIELD_CNT
};

static struct is_field csi_bns_fields[CSIS_BNS_REG_FIELD_CNT] = {
	/* BNS_BYPASS */
	{"BYPASS", 0, 1, RW, 0x1},
	/* BNS_CONFIG */
	{"BITTAGE", 16, 4, RW, 0x0},
	{"FACTOR_Y", 8, 3, RW, 0x0},
	{"FACTOR_X", 0, 3, RW, 0x0},
	/* BNS_INPUTSIZE */
	{"INPUT_TOTAL_HEIGHT", 16, 14, RW, 0x20},
	{"INPUT_TOTAL_WIDTH", 0, 14, RW, 0x20},
	/* BNS_OUTPUTSIZE */
	{"OUTPUT_TOTAL_HEIGHT", 16, 14, RW, 0x20},
	{"OUTPUT_TOTAL_WIDTH", 0, 14, RW, 0x20},
	/* BNS_WEIGHT_0_X */
	{"WEIGHT_0_3", 24, 8, RW, 0x0},
	{"WEIGHT_0_2", 16, 8, RW, 0x0},
	{"WEIGHT_0_1", 8, 8, RW, 0x0},
	{"WEIGHT_0_0", 0, 8, RW, 0x0},
	/* BNS_WEIGHT_0_4 */
	{"WEIGHT_0_4", 0, 8, RW, 0x0},
	/* BNS_STREAM_CRC */
	{"CRC_RESULT", 8, 8, RO, 0x0},
	{"CRC_SEED", 0, 8, RW, 0x0},
};

#if IS_ENABLED(CONFIG_PABLO_KUNIT_TEST)
struct pablo_kunit_hw_csi_func {
	int (*csi_hw_bns_dump)(u32 __iomem *reg);
	int (*csi_hw_clear_fro_count)(u32 __iomem *dma_top_reg, u32 __iomem *vc_reg);
	int (*csi_hw_fro_dump)(u32 __iomem *reg);
	int (*csi_hw_g_dma_common_frame_id)(u32 __iomem *base_reg, u32 batch_num, u32 *frame_id);
	void (*csi_hw_g_ebuf_irq_src)(u32 __iomem *base_reg, struct csis_irq_src *src, int ebuf_ch,
			unsigned int offset_fake_frame_done);
	int (*csi_hw_g_irq_src)(u32 __iomem *base_reg, struct csis_irq_src *src, bool clear);
	u32 (*csi_hw_g_frameptr)(u32 __iomem *base_reg, u32 vc);
	u32 (*csi_hw_g_mapped_phy_port)(u32 csi_ch);
	bool (*csi_hw_g_output_cur_dma_enable)(u32 __iomem *base_reg, u32 vc);
	void (*csi_hw_reset_bns)(u32 __iomem *reg);
	void (*csi_hw_s_bns_ch)(u32 __iomem *reg, u32 ch);
	int (*csi_hw_s_cfg_ebuf)(u32 __iomem *base_reg, u32 ebuf_ch, u32 vc, u32 width,
			u32 height);
	int (*csi_hw_s_dma_common_dynamic)(u32 __iomem *base_reg, size_t size, unsigned int dma_ch);
	int (*csi_hw_s_dma_common_pattern_enable)(u32 __iomem *base_reg,
			u32 width, u32 height, u32 fps, u32 clk);
	void (*csi_hw_s_dma_common_pattern_disable)(u32 __iomem *base_reg);
	void (*csi_hw_s_dma_input_mux)(void __iomem *mux_regs, u32 idx_wdma, u32 wdma_index,
				       bool bns_en, u32 bns_dma_mux_val, u32 csi_ch, int otf_ch,
				       int otf_out_id, int *link_vc_list,
				       struct is_wdma_info *wdma_info);
	void (*csi_hw_s_init_input_mux)(void __iomem *mux_regs, u32 idx_wdma, u32 index);
};
struct pablo_kunit_hw_csi_func *pablo_kunit_get_hw_csi_test(void);
#endif
#endif /* IS_HW_CSIS_V8_0_H */
