# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)

# Exynos DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS_DEVFREQ)		+= exynos_devfreq.o
exynos_devfreq-y				+= exynos-devfreq.o
exynos_devfreq-y				+= governor_nop.o

obj-$(CONFIG_EXYNOS_LEALT_DVFS) 	+= lealt-gov.o
obj-$(CONFIG_EXYNOS_LEALT_DVFS) 	+= lealt-mon.o

# Test
obj-$(CONFIG_DVFS_EXYNOS_KUNIT_TEST) += test/
