# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_SOC_S5E9955) += \
        s5e9955-erd9955.dtbo		\
        s5e9955-erd9955_rev1.dtbo		\
        s5e9955-erd9955_rev2.dtbo		\
        s5e9955-erd9955_rev3.dtbo		\
        s5e9955-erd9955_16k.dtbo	\
        s5e9955-erd9955_16k_rev1.dtbo	\
        s5e9955-erd9955_16k_rev2.dtbo	\
        s5e9955-erd9955_16k_rev3.dtbo	\
        s5e9955-erd9955_emul.dtbo	\

always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
