#
# Makefile for HTS
#

obj-$(CONFIG_HTS)	+= hts.o
hts-$(CONFIG_HTS)	+= hts_entry.o hts_logic.o hts_backup.o hts_pmu.o hts_core.o hts_devfs.o hts_sysfs.o hts_vh.o hts_ops.o hts_var.o hts_etc.o hts_backup.o hts_logic.o hts_common.o
hts-$(CONFIG_HTS_EXT) += hts_ext_dev.o

