dtbo-y += a56x_eur_open_w00_r04.dtbo
dtbo-y += a56x_eur_open_w00_r02.dtbo
dtbo-y += a56x_eur_open_w00_r01.dtbo
dtbo-y += a56x_eur_open_w00_r00.dtbo
# SPDX-License-Identifier: GPL-2.0

always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo

