# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PHY_EXYNOS_DP_VIDEO)	+= phy-exynos-dp-video.o
obj-$(CONFIG_PHY_EXYNOS_MIPI_VIDEO)	+= phy-exynos-mipi-video.o
obj-$(CONFIG_PHY_EXYNOS_MIPI_DSIM)      += phy-exynos-mipi-dsim.o
obj-$(CONFIG_PHY_EXYNOS_MIPI)           += phy-exynos-mipi.o
obj-$(CONFIG_PHY_EXYNOS_PCIE)		+= phy-exynos-pcie.o
obj-$(CONFIG_PHY_SAMSUNG_UFS)		+= phy-exynos-ufs.o
phy-exynos-ufs-y			+= phy-samsung-ufs.o
phy-exynos-ufs-y			+= phy-exynos7-ufs.o
phy-exynos-ufs-y			+= phy-exynosautov9-ufs.o
phy-exynos-ufs-y			+= phy-fsd-ufs.o

obj-$(CONFIG_PHY_EXYNOS5250_SATA)	+= phy-exynos5250-sata.o
