# SPDX-License-Identifier: GPL-2.0
subdir-ccflags-y += -I${ROOT_DIR}/${EXYNOS_SOC_DIR}/include/sound/samsung

obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8855_AUDIO) += exynos8855_audio.o

obj-$(CONFIG_SND_SOC_SAMSUNG_AUDIO) += sec_audio_sysfs.o sec_audio_debug.o