# SPDX-License-Identifier: GPL-2.0
#
# USB peripheral controller drivers
# USB Functions
obj-$(CONFIG_SEC_USB_HOOK) += sec_usb_hook.o

subdir-ccflags-y += -I${ROOT_DIR}/${KERNEL_DIR}/drivers/usb/dwc3
