# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SEC_BOOTSTAT)	+= sec_bootstat.o
obj-$(CONFIG_SEC_KEY_NOTIFIER)	+= sec_key_notifier.o
obj-$(CONFIG_CRASH_KEY_USER)	+= sec_crash_key_user.o
obj-$(CONFIG_HARD_RESET_HOOK)	+= sec_hard_reset_hook.o

# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SEC_REBOOT)        += sec_reboot.o

# Samsung sec sysfs Feature
obj-$(CONFIG_DRV_SAMSUNG)	+= sec_class.o

