#
# Copyright (c) 2012 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_MSCL_EXYNOS_KUNIT_TEST) += mscl_exynos_test.o

mscl_exynos_test-y += mscl_kunit_test.o

ccflags-y += -I$(srctree)/$(src)/../
