# SPDX-License-Identifier: GPL-2.0
# SAMSUNG pmic pinmux support

obj-$(CONFIG_PINCTRL_S2P) += s2p_pinctrl.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPS28) += s2mps28_pinctrl.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPM07_9945) += s2mpm07_pinctrl_9945.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2SE911) += s2se911_pinctrl.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPA05) += s2mpa05_pinctrl.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPU15) += s2mpu15_pinctrl.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPU16) += s2mpu16_pinctrl.o